// ─── TPA Aging Report — Constants & Mock Data ────────────────────────────────

export {
  fmtINR, fmtDate, fmtDateTime, fmtINRFull,
  CLAIM_TYPES, RISK_LEVELS, AGING_BUCKETS,
  INSURANCE_TPAS, DEPARTMENTS, DOCTORS, BRANCHES,
  CLAIM_STATUSES,
} from '../IC/ICConstants';

// ─── TAR KPI Config — 10 KPIs ────────────────────────────────────────────────
export const TAR_KPI_CONFIG = [
  {
    id: 'totalOutstanding', label: 'Total TPA Outstanding', value: 118420000,
    format: 'lakh', trend: -4.2, color: '#6366f1', icon: 'IndianRupee',
    sub: '1,847 claims', aiFlag: false, trendLabel: 'vs last month',
  },
  {
    id: 'bucket0_30', label: '0–30 Days', value: 28640000,
    format: 'lakh', trend: 8.1, color: '#10b981', icon: 'Clock',
    sub: '421 claims', aiFlag: false, trendLabel: 'new entries',
  },
  {
    id: 'bucket31_60', label: '31–60 Days', value: 31820000,
    format: 'lakh', trend: 3.4, color: '#f59e0b', icon: 'Timer',
    sub: '387 claims', aiFlag: false, trendLabel: 'vs last month',
  },
  {
    id: 'bucket61_90', label: '61–90 Days', value: 24180000,
    format: 'lakh', trend: -6.8, color: '#f97316', icon: 'AlertCircle',
    sub: '298 claims', aiFlag: true, trendLabel: 'improvement',
  },
  {
    id: 'bucket91_180', label: '91–180 Days', value: 21640000,
    format: 'lakh', trend: -9.4, color: '#ef4444', icon: 'AlertTriangle',
    sub: '267 claims', aiFlag: true, trendLabel: 'reduction',
  },
  {
    id: 'bucket180plus', label: '>180 Days', value: 12140000,
    format: 'lakh', trend: -18.6, color: '#dc2626', icon: 'AlertOctagon',
    sub: '143 claims', aiFlag: true, trendLabel: 'recovered',
  },
  {
    id: 'recoveryRate', label: 'Recovery Rate', value: 87.3,
    format: 'pct', trend: 2.1, color: '#0d9488', icon: 'TrendingUp',
    sub: 'vs 85.2% target', aiFlag: false, trendLabel: 'vs last quarter',
  },
  {
    id: 'deniedExposure', label: 'Denied Exposure', value: 7430000,
    format: 'lakh', trend: -14.1, color: '#be185d', icon: 'XCircle',
    sub: '89 claims', aiFlag: true, trendLabel: 'recovered',
  },
  {
    id: 'avgSettleDays', label: 'Avg Settlement Days', value: 34,
    format: 'num', trend: -8, color: '#8b5cf6', icon: 'CalendarClock',
    sub: 'Target: 30d', aiFlag: true, trendLabel: 'days vs last month',
  },
  {
    id: 'highRiskTPAs', label: 'High-Risk TPAs', value: 6,
    format: 'num', trend: -2, color: '#ea580c', icon: 'ShieldAlert',
    sub: 'AI flagged', aiFlag: true, trendLabel: 'vs last week',
  },
];

// ─── Workflow Statuses ────────────────────────────────────────────────────────
export const WORKFLOW_STATUSES = {
  AWAITING_SUBMISSION:   { label: 'Awaiting Submission',   bg: 'bg-slate-100 dark:bg-slate-800',      text: 'text-slate-600 dark:text-slate-300',   dot: '#94a3b8' },
  UNDER_TPA_REVIEW:      { label: 'Under TPA Review',      bg: 'bg-blue-100 dark:bg-blue-900/30',     text: 'text-blue-700 dark:text-blue-400',     dot: '#3b82f6' },
  PENDING_TPA_RESPONSE:  { label: 'Pending TPA Response',  bg: 'bg-violet-100 dark:bg-violet-900/30', text: 'text-violet-700 dark:text-violet-400', dot: '#8b5cf6' },
  AWAITING_SETTLEMENT:   { label: 'Awaiting Settlement',   bg: 'bg-amber-100 dark:bg-amber-900/30',   text: 'text-amber-700 dark:text-amber-400',   dot: '#f59e0b' },
  APPEAL_IN_PROGRESS:    { label: 'Appeal in Progress',    bg: 'bg-orange-100 dark:bg-orange-900/30', text: 'text-orange-700 dark:text-orange-400', dot: '#f97316' },
  ESCALATED:             { label: 'Escalated',             bg: 'bg-red-100 dark:bg-red-900/30',       text: 'text-red-700 dark:text-red-400',       dot: '#ef4444' },
  DOCUMENTS_PENDING:     { label: 'Documents Pending',     bg: 'bg-yellow-100 dark:bg-yellow-900/30', text: 'text-yellow-700 dark:text-yellow-400', dot: '#eab308' },
  PARTIAL_SETTLEMENT:    { label: 'Partial Settlement',    bg: 'bg-teal-100 dark:bg-teal-900/30',     text: 'text-teal-700 dark:text-teal-400',     dot: '#14b8a6' },
  CLOSED:                { label: 'Closed',                bg: 'bg-emerald-100 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-400', dot: '#10b981' },
  RECONCILED:            { label: 'Reconciled',            bg: 'bg-indigo-100 dark:bg-indigo-900/30', text: 'text-indigo-700 dark:text-indigo-400', dot: '#6366f1' },
};

// ─── Follow-up Statuses ───────────────────────────────────────────────────────
export const FOLLOWUP_STATUSES = {
  PENDING:     { label: 'Pending',     bg: 'bg-slate-100 dark:bg-slate-800',      text: 'text-slate-600 dark:text-slate-300' },
  IN_PROGRESS: { label: 'In Progress', bg: 'bg-blue-100 dark:bg-blue-900/30',     text: 'text-blue-700 dark:text-blue-400'   },
  ESCALATED:   { label: 'Escalated',   bg: 'bg-red-100 dark:bg-red-900/30',       text: 'text-red-700 dark:text-red-400'     },
  RESOLVED:    { label: 'Resolved',    bg: 'bg-emerald-100 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-400' },
};

// ─── Settlement Statuses ──────────────────────────────────────────────────────
export const SETTLEMENT_STATUSES = {
  PENDING:        { label: 'Pending',        bg: 'bg-amber-100 dark:bg-amber-900/30',   text: 'text-amber-700 dark:text-amber-400'   },
  PARTIAL:        { label: 'Partial',        bg: 'bg-teal-100 dark:bg-teal-900/30',     text: 'text-teal-700 dark:text-teal-400'     },
  SETTLED:        { label: 'Settled',        bg: 'bg-emerald-100 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-400' },
  RECONCILED:     { label: 'Reconciled',     bg: 'bg-indigo-100 dark:bg-indigo-900/30', text: 'text-indigo-700 dark:text-indigo-400' },
  NOT_APPLICABLE: { label: 'N/A',            bg: 'bg-slate-100 dark:bg-slate-800',      text: 'text-slate-500 dark:text-slate-400'   },
};

// ─── Aging Bucket Color Map ───────────────────────────────────────────────────
export const AGING_BUCKET_COLORS = {
  current: '#10b981',
  days31:  '#f59e0b',
  days61:  '#f97316',
  days91:  '#ef4444',
  days121: '#dc2626',
};

// ─── Mock Aging Claims — 32 records ──────────────────────────────────────────
export const MOCK_AGING_CLAIMS = [
  // ── 0-30 days (8 records) ─────────────────────────────────────────────────
  {
    id: 'CLM-2026-01001',
    patientName: 'Arjun Mehta',
    uhid: 'HC-005201',
    invoiceNo: 'INV-2026-02001',
    arEntryNo: 'AR-2026-00901',
    tpa: 'HDFC ERGO Health',
    claimType: 'CASHLESS',
    department: 'Cardiology',
    doctor: 'Dr. Anand Krishnan',
    branch: 'Main Campus',
    diagnosis: 'Coronary Artery Disease — Stenting',
    admissionDate: '2026-05-01',
    dischargeDate: '2026-05-06',
    claimSubmitDate: '2026-05-07',
    claimAmount: 485000,
    approvedAmount: 485000,
    deniedAmount: 0,
    outstandingAmount: 485000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 13,
    followUpCount: 1,
    lastFollowUp: '2026-05-15',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'UNDER_TPA_REVIEW',
    recoveryProbability: 94,
    riskLevel: 'LOW',
    denialReason: null,
    status: 'APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-05-01', event: 'Patient Admitted', user: 'Admission Desk', type: 'admission' },
      { date: '2026-05-03', event: 'Preauth Approved — ₹4.85L', user: 'HDFC ERGO Health', type: 'approval' },
      { date: '2026-05-06', event: 'Patient Discharged', user: 'Dr. Anand Krishnan', type: 'discharge' },
      { date: '2026-05-07', event: 'Claim Submitted (Cashless)', user: 'Claims Team', type: 'submission' },
      { date: '2026-05-14', event: 'Claim Approved — ₹4.85L', user: 'HDFC ERGO Health', type: 'approval' },
      { date: '2026-05-15', event: 'Follow-up: Awaiting settlement', user: 'AR Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-01002',
    patientName: 'Priya Chandrasekhar',
    uhid: 'HC-005178',
    invoiceNo: 'INV-2026-02002',
    arEntryNo: 'AR-2026-00902',
    tpa: 'Bajaj Allianz Health',
    claimType: 'TPA',
    department: 'Orthopedics',
    doctor: 'Dr. Suresh Nair',
    branch: 'North Wing',
    diagnosis: 'Total Knee Replacement',
    admissionDate: '2026-05-03',
    dischargeDate: '2026-05-09',
    claimSubmitDate: '2026-05-10',
    claimAmount: 612000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 612000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 10,
    followUpCount: 0,
    lastFollowUp: null,
    followUpStatus: 'PENDING',
    settlementStatus: 'PENDING',
    workflowStatus: 'UNDER_TPA_REVIEW',
    recoveryProbability: 91,
    riskLevel: 'LOW',
    denialReason: null,
    status: 'SUBMITTED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-05-03', event: 'Patient Admitted', user: 'Admission Desk', type: 'admission' },
      { date: '2026-05-09', event: 'Patient Discharged', user: 'Dr. Suresh Nair', type: 'discharge' },
      { date: '2026-05-10', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
    ],
  },
  {
    id: 'CLM-2026-01003',
    patientName: 'Rajan Iyer',
    uhid: 'HC-005142',
    invoiceNo: 'INV-2026-02003',
    arEntryNo: 'AR-2026-00903',
    tpa: 'Star Health Insurance',
    claimType: 'TPA',
    department: 'General Surgery',
    doctor: 'Dr. Meena Pillai',
    branch: 'South Clinic',
    diagnosis: 'Laparoscopic Appendectomy',
    admissionDate: '2026-05-05',
    dischargeDate: '2026-05-07',
    claimSubmitDate: '2026-05-08',
    claimAmount: 168000,
    approvedAmount: 168000,
    deniedAmount: 0,
    outstandingAmount: 168000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 12,
    followUpCount: 1,
    lastFollowUp: '2026-05-16',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'AWAITING_SETTLEMENT',
    recoveryProbability: 96,
    riskLevel: 'LOW',
    denialReason: null,
    status: 'APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-16',
    timeline: [
      { date: '2026-05-05', event: 'Patient Admitted', user: 'Admission Desk', type: 'admission' },
      { date: '2026-05-07', event: 'Patient Discharged', user: 'Dr. Meena Pillai', type: 'discharge' },
      { date: '2026-05-08', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-05-12', event: 'Claim Approved — ₹1.68L', user: 'Star Health Insurance', type: 'approval' },
      { date: '2026-05-16', event: 'Follow-up: Payment reference requested', user: 'AR Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-01004',
    patientName: 'Sunita Deshpande',
    uhid: 'HC-005089',
    invoiceNo: 'INV-2026-02004',
    arEntryNo: 'AR-2026-00904',
    tpa: 'ICICI Lombard',
    claimType: 'CASHLESS',
    department: 'Neurology',
    doctor: 'Dr. Rajiv Menon',
    branch: 'East Block',
    diagnosis: 'Epilepsy — Monitoring & Medication Adjustment',
    admissionDate: '2026-05-04',
    dischargeDate: '2026-05-08',
    claimSubmitDate: '2026-05-09',
    claimAmount: 243000,
    approvedAmount: 220000,
    deniedAmount: 23000,
    outstandingAmount: 220000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 11,
    followUpCount: 1,
    lastFollowUp: '2026-05-17',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'AWAITING_SETTLEMENT',
    recoveryProbability: 88,
    riskLevel: 'LOW',
    denialReason: 'Exceeded Package Limit',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-17',
    timeline: [
      { date: '2026-05-04', event: 'Patient Admitted', user: 'Admission Desk', type: 'admission' },
      { date: '2026-05-08', event: 'Patient Discharged', user: 'Dr. Rajiv Menon', type: 'discharge' },
      { date: '2026-05-09', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-05-15', event: 'Partial Approval — ₹2.20L (₹23K denied)', user: 'ICICI Lombard', type: 'approval' },
      { date: '2026-05-17', event: 'Follow-up: Contesting denial portion', user: 'AR Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-01005',
    patientName: 'Venkat Subramanian',
    uhid: 'HC-005061',
    invoiceNo: 'INV-2026-02005',
    arEntryNo: 'AR-2026-00905',
    tpa: 'Aditya Birla Health',
    claimType: 'CORPORATE',
    department: 'Pediatrics',
    doctor: 'Dr. Lakshmi Devi',
    branch: 'Main Campus',
    diagnosis: 'Acute Pneumonia — Paediatric ICU',
    admissionDate: '2026-05-08',
    dischargeDate: '2026-05-13',
    claimSubmitDate: '2026-05-14',
    claimAmount: 198000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 198000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 6,
    followUpCount: 0,
    lastFollowUp: null,
    followUpStatus: 'PENDING',
    settlementStatus: 'PENDING',
    workflowStatus: 'UNDER_TPA_REVIEW',
    recoveryProbability: 89,
    riskLevel: 'LOW',
    denialReason: null,
    status: 'SUBMITTED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-05-08', event: 'Patient Admitted', user: 'Paediatric OPD', type: 'admission' },
      { date: '2026-05-13', event: 'Patient Discharged', user: 'Dr. Lakshmi Devi', type: 'discharge' },
      { date: '2026-05-14', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
    ],
  },
  {
    id: 'CLM-2026-01006',
    patientName: 'Kavita Rao',
    uhid: 'HC-005031',
    invoiceNo: 'INV-2026-02006',
    arEntryNo: 'AR-2026-00906',
    tpa: 'Medi Assist TPA',
    claimType: 'TPA',
    department: 'Gynecology',
    doctor: 'Dr. Kavita Iyer',
    branch: 'Specialty Center',
    diagnosis: 'Hysterectomy — Laparoscopic',
    admissionDate: '2026-05-02',
    dischargeDate: '2026-05-07',
    claimSubmitDate: '2026-05-08',
    claimAmount: 342000,
    approvedAmount: 342000,
    deniedAmount: 0,
    outstandingAmount: 342000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 12,
    followUpCount: 2,
    lastFollowUp: '2026-05-18',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'AWAITING_SETTLEMENT',
    recoveryProbability: 93,
    riskLevel: 'LOW',
    denialReason: null,
    status: 'APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-05-02', event: 'Patient Admitted', user: 'Gynaecology OPD', type: 'admission' },
      { date: '2026-05-07', event: 'Patient Discharged', user: 'Dr. Kavita Iyer', type: 'discharge' },
      { date: '2026-05-08', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-05-13', event: 'Claim Approved — ₹3.42L', user: 'Medi Assist TPA', type: 'approval' },
      { date: '2026-05-16', event: 'Follow-up #1: Settlement ETA requested', user: 'AR Team', type: 'followup' },
      { date: '2026-05-18', event: 'Follow-up #2: Escalation sent', user: 'AR Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-01007',
    patientName: 'Mohan Reddy',
    uhid: 'HC-004987',
    invoiceNo: 'INV-2026-02007',
    arEntryNo: 'AR-2026-00907',
    tpa: 'New India Assurance',
    claimType: 'REIMBURSEMENT',
    department: 'Urology',
    doctor: 'Dr. Ashok Verma',
    branch: 'East Block',
    diagnosis: 'Kidney Stone — PCNL Procedure',
    admissionDate: '2026-05-06',
    dischargeDate: '2026-05-10',
    claimSubmitDate: '2026-05-12',
    claimAmount: 287000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 287000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 8,
    followUpCount: 0,
    lastFollowUp: null,
    followUpStatus: 'PENDING',
    settlementStatus: 'PENDING',
    workflowStatus: 'UNDER_TPA_REVIEW',
    recoveryProbability: 85,
    riskLevel: 'LOW',
    denialReason: null,
    status: 'SUBMITTED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-05-06', event: 'Patient Admitted', user: 'Urology OPD', type: 'admission' },
      { date: '2026-05-10', event: 'Patient Discharged', user: 'Dr. Ashok Verma', type: 'discharge' },
      { date: '2026-05-12', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
    ],
  },
  {
    id: 'CLM-2026-01008',
    patientName: 'Nalini Krishnamurthy',
    uhid: 'HC-004941',
    invoiceNo: 'INV-2026-02008',
    arEntryNo: 'AR-2026-00908',
    tpa: 'Oriental Insurance',
    claimType: 'TPA',
    department: 'Gastroenterology',
    doctor: 'Dr. Rajeev Gupta',
    branch: 'Main Campus',
    diagnosis: 'Acute Pancreatitis',
    admissionDate: '2026-05-07',
    dischargeDate: '2026-05-14',
    claimSubmitDate: '2026-05-15',
    claimAmount: 412000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 412000,
    settledAmount: 0,
    agingBucket: 'current',
    agingDays: 5,
    followUpCount: 0,
    lastFollowUp: null,
    followUpStatus: 'PENDING',
    settlementStatus: 'PENDING',
    workflowStatus: 'UNDER_TPA_REVIEW',
    recoveryProbability: 87,
    riskLevel: 'LOW',
    denialReason: null,
    status: 'SUBMITTED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-05-07', event: 'Patient Admitted', user: 'Emergency', type: 'admission' },
      { date: '2026-05-14', event: 'Patient Discharged', user: 'Dr. Rajeev Gupta', type: 'discharge' },
      { date: '2026-05-15', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
    ],
  },

  // ── 31-60 days (7 records) ────────────────────────────────────────────────
  {
    id: 'CLM-2026-00901',
    patientName: 'Suresh Kumar Patel',
    uhid: 'HC-004812',
    invoiceNo: 'INV-2026-01901',
    arEntryNo: 'AR-2026-00801',
    tpa: 'Star Health Insurance',
    claimType: 'TPA',
    department: 'Cardiology',
    doctor: 'Dr. Anand Krishnan',
    branch: 'Main Campus',
    diagnosis: 'Atrial Fibrillation — Ablation',
    admissionDate: '2026-04-10',
    dischargeDate: '2026-04-15',
    claimSubmitDate: '2026-04-17',
    claimAmount: 524000,
    approvedAmount: 498000,
    deniedAmount: 26000,
    outstandingAmount: 498000,
    settledAmount: 0,
    agingBucket: 'days31',
    agingDays: 33,
    followUpCount: 3,
    lastFollowUp: '2026-05-12',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'PENDING_TPA_RESPONSE',
    recoveryProbability: 82,
    riskLevel: 'MEDIUM',
    denialReason: 'Exceeded Package Limit',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-12',
    timeline: [
      { date: '2026-04-10', event: 'Patient Admitted', user: 'Cardiology OPD', type: 'admission' },
      { date: '2026-04-12', event: 'Preauth Approved — ₹5.24L', user: 'Star Health Insurance', type: 'approval' },
      { date: '2026-04-15', event: 'Patient Discharged', user: 'Dr. Anand Krishnan', type: 'discharge' },
      { date: '2026-04-17', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-05-01', event: 'Partial Approval — ₹4.98L (₹26K denied)', user: 'Star Health Insurance', type: 'approval' },
      { date: '2026-05-07', event: 'Follow-up #1: Settlement ETA', user: 'AR Team', type: 'followup' },
      { date: '2026-05-12', event: 'Follow-up #3: No response from TPA', user: 'AR Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00902',
    patientName: 'Ananya Bose',
    uhid: 'HC-004768',
    invoiceNo: 'INV-2026-01902',
    arEntryNo: 'AR-2026-00802',
    tpa: 'CGHS',
    claimType: 'CGHS',
    department: 'Oncology',
    doctor: 'Dr. Kavita Iyer',
    branch: 'Specialty Center',
    diagnosis: 'Breast Cancer — Chemotherapy Cycle 6',
    admissionDate: '2026-04-08',
    dischargeDate: '2026-04-15',
    claimSubmitDate: '2026-04-18',
    claimAmount: 876000,
    approvedAmount: 720000,
    deniedAmount: 156000,
    outstandingAmount: 720000,
    settledAmount: 0,
    agingBucket: 'days31',
    agingDays: 32,
    followUpCount: 4,
    lastFollowUp: '2026-05-14',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 71,
    riskLevel: 'MEDIUM',
    denialReason: 'Exceeded Package Limit',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-14',
    timeline: [
      { date: '2026-04-08', event: 'Patient Admitted', user: 'Oncology OPD', type: 'admission' },
      { date: '2026-04-15', event: 'Patient Discharged', user: 'Dr. Kavita Iyer', type: 'discharge' },
      { date: '2026-04-18', event: 'Claim Submitted to CGHS', user: 'Claims Team', type: 'submission' },
      { date: '2026-05-06', event: 'Partial Approval — ₹7.20L (₹1.56L denied)', user: 'CGHS Office', type: 'approval' },
      { date: '2026-05-10', event: 'Follow-up #2: No settlement', user: 'AR Team', type: 'followup' },
      { date: '2026-05-14', event: 'Escalated to CGHS Director', user: 'Claims Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00903',
    patientName: 'Deepak Nambiar',
    uhid: 'HC-004712',
    invoiceNo: 'INV-2026-01903',
    arEntryNo: 'AR-2026-00803',
    tpa: 'Paramount TPA',
    claimType: 'TPA',
    department: 'Nephrology',
    doctor: 'Dr. Sunitha Rao',
    branch: 'Main Campus',
    diagnosis: 'Chronic Kidney Disease — Dialysis',
    admissionDate: '2026-04-12',
    dischargeDate: '2026-04-20',
    claimSubmitDate: '2026-04-22',
    claimAmount: 318000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 318000,
    settledAmount: 0,
    agingBucket: 'days31',
    agingDays: 28,
    followUpCount: 2,
    lastFollowUp: '2026-05-10',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'DOCUMENTS_PENDING',
    recoveryProbability: 67,
    riskLevel: 'HIGH',
    denialReason: null,
    status: 'PENDING_DOCS',
    glPosted: false,
    reconciled: false,
    lastUpdated: '2026-05-10',
    timeline: [
      { date: '2026-04-12', event: 'Patient Admitted', user: 'Nephrology OPD', type: 'admission' },
      { date: '2026-04-20', event: 'Patient Discharged', user: 'Dr. Sunitha Rao', type: 'discharge' },
      { date: '2026-04-22', event: 'Claim Preparation Started', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-28', event: 'Documents incomplete — Dialysis records missing', user: 'Claims Team', type: 'followup' },
      { date: '2026-05-10', event: 'Follow-up #2: Still awaiting dialysis records', user: 'AR Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00904',
    patientName: 'Ramya Venkatesh',
    uhid: 'HC-004658',
    invoiceNo: 'INV-2026-01904',
    arEntryNo: 'AR-2026-00804',
    tpa: 'ICICI Lombard',
    claimType: 'CASHLESS',
    department: 'ICU',
    doctor: 'Dr. Ashok Verma',
    branch: 'Main Campus',
    diagnosis: 'Septic Shock — Multi-organ support',
    admissionDate: '2026-04-09',
    dischargeDate: '2026-04-18',
    claimSubmitDate: '2026-04-19',
    claimAmount: 742000,
    approvedAmount: 742000,
    deniedAmount: 0,
    outstandingAmount: 742000,
    settledAmount: 0,
    agingBucket: 'days31',
    agingDays: 31,
    followUpCount: 3,
    lastFollowUp: '2026-05-13',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'AWAITING_SETTLEMENT',
    recoveryProbability: 86,
    riskLevel: 'MEDIUM',
    denialReason: null,
    status: 'APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-13',
    timeline: [
      { date: '2026-04-09', event: 'Emergency Admission — ICU', user: 'Emergency', type: 'admission' },
      { date: '2026-04-10', event: 'Preauth Approved (Emergency) — ₹7.42L', user: 'ICICI Lombard', type: 'approval' },
      { date: '2026-04-18', event: 'Patient Discharged', user: 'Dr. Ashok Verma', type: 'discharge' },
      { date: '2026-04-19', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-30', event: 'Claim Approved — ₹7.42L', user: 'ICICI Lombard', type: 'approval' },
      { date: '2026-05-07', event: 'Follow-up #1: Settlement ETA', user: 'AR Team', type: 'followup' },
      { date: '2026-05-13', event: 'Follow-up #3: Escalation raised', user: 'Claims Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00905',
    patientName: 'Harish Krishnan',
    uhid: 'HC-004598',
    invoiceNo: 'INV-2026-01905',
    arEntryNo: 'AR-2026-00805',
    tpa: 'Vipul Medcorp TPA',
    claimType: 'CORPORATE',
    department: 'General Surgery',
    doctor: 'Dr. Meena Pillai',
    branch: 'North Wing',
    diagnosis: 'Hernia Repair — Open Mesh',
    admissionDate: '2026-04-14',
    dischargeDate: '2026-04-17',
    claimSubmitDate: '2026-04-18',
    claimAmount: 142000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 142000,
    settledAmount: 0,
    agingBucket: 'days31',
    agingDays: 32,
    followUpCount: 2,
    lastFollowUp: '2026-05-11',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'UNDER_TPA_REVIEW',
    recoveryProbability: 78,
    riskLevel: 'MEDIUM',
    denialReason: null,
    status: 'UNDER_REVIEW',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-11',
    timeline: [
      { date: '2026-04-14', event: 'Patient Admitted', user: 'Surgical OPD', type: 'admission' },
      { date: '2026-04-17', event: 'Patient Discharged', user: 'Dr. Meena Pillai', type: 'discharge' },
      { date: '2026-04-18', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-28', event: 'Query from TPA: Additional records', user: 'Vipul Medcorp TPA', type: 'followup' },
      { date: '2026-05-11', event: 'Documents uploaded, awaiting review', user: 'Claims Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00906',
    patientName: 'Sudha Ramachandran',
    uhid: 'HC-004521',
    invoiceNo: 'INV-2026-01906',
    arEntryNo: 'AR-2026-00806',
    tpa: 'ECHS Board',
    claimType: 'ECHS',
    department: 'Psychiatry',
    doctor: 'Dr. Priya Sharma',
    branch: 'Specialty Center',
    diagnosis: 'Major Depressive Disorder — Inpatient',
    admissionDate: '2026-04-11',
    dischargeDate: '2026-04-22',
    claimSubmitDate: '2026-04-24',
    claimAmount: 238000,
    approvedAmount: 210000,
    deniedAmount: 28000,
    outstandingAmount: 210000,
    settledAmount: 0,
    agingBucket: 'days31',
    agingDays: 26,
    followUpCount: 2,
    lastFollowUp: '2026-05-08',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'AWAITING_SETTLEMENT',
    recoveryProbability: 80,
    riskLevel: 'MEDIUM',
    denialReason: 'Policy Exclusion',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-08',
    timeline: [
      { date: '2026-04-11', event: 'Patient Admitted', user: 'Psychiatry OPD', type: 'admission' },
      { date: '2026-04-22', event: 'Patient Discharged', user: 'Dr. Priya Sharma', type: 'discharge' },
      { date: '2026-04-24', event: 'Claim Submitted to ECHS', user: 'Claims Team', type: 'submission' },
      { date: '2026-05-04', event: 'Partial Approval — ₹2.10L (₹28K excluded)', user: 'ECHS Board', type: 'approval' },
      { date: '2026-05-08', event: 'Follow-up #2: Settlement ETD', user: 'AR Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00907',
    patientName: 'Girish Shetty',
    uhid: 'HC-004468',
    invoiceNo: 'INV-2026-01907',
    arEntryNo: 'AR-2026-00807',
    tpa: 'Health India TPA',
    claimType: 'TPA',
    department: 'Radiology',
    doctor: 'Dr. Suresh Nair',
    branch: 'East Block',
    diagnosis: 'Spinal Cord Compression — Decompression Surgery',
    admissionDate: '2026-04-06',
    dischargeDate: '2026-04-14',
    claimSubmitDate: '2026-04-15',
    claimAmount: 683000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 683000,
    settledAmount: 0,
    agingBucket: 'days31',
    agingDays: 35,
    followUpCount: 3,
    lastFollowUp: '2026-05-15',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'UNDER_TPA_REVIEW',
    recoveryProbability: 74,
    riskLevel: 'MEDIUM',
    denialReason: null,
    status: 'UNDER_REVIEW',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-15',
    timeline: [
      { date: '2026-04-06', event: 'Patient Admitted', user: 'Ortho OPD', type: 'admission' },
      { date: '2026-04-14', event: 'Patient Discharged', user: 'Dr. Suresh Nair', type: 'discharge' },
      { date: '2026-04-15', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-25', event: 'Additional documents requested', user: 'Health India TPA', type: 'followup' },
      { date: '2026-05-05', event: 'Documents uploaded', user: 'Claims Team', type: 'followup' },
      { date: '2026-05-15', event: 'Follow-up #3: Under review still', user: 'AR Manager', type: 'followup' },
    ],
  },

  // ── 61-90 days (7 records) ────────────────────────────────────────────────
  {
    id: 'CLM-2026-00801',
    patientName: 'Rajesh Kumar Sharma',
    uhid: 'HC-004231',
    invoiceNo: 'INV-2026-01801',
    arEntryNo: 'AR-2026-00701',
    tpa: 'Star Health Insurance',
    claimType: 'TPA',
    department: 'Cardiology',
    doctor: 'Dr. Anand Krishnan',
    branch: 'Main Campus',
    diagnosis: 'Acute Myocardial Infarction',
    admissionDate: '2026-03-20',
    dischargeDate: '2026-03-26',
    claimSubmitDate: '2026-03-28',
    claimAmount: 348500,
    approvedAmount: 298000,
    deniedAmount: 50500,
    outstandingAmount: 298000,
    settledAmount: 0,
    agingBucket: 'days61',
    agingDays: 53,
    followUpCount: 5,
    lastFollowUp: '2026-05-16',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 64,
    riskLevel: 'HIGH',
    denialReason: 'Incomplete Documentation',
    status: 'UNDER_REVIEW',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-16',
    timeline: [
      { date: '2026-03-20', event: 'Patient Admitted — CICU', user: 'Emergency', type: 'admission' },
      { date: '2026-03-22', event: 'Preauth Approved — ₹3.5L', user: 'Star Health Insurance', type: 'approval' },
      { date: '2026-03-26', event: 'Patient Discharged', user: 'Dr. Anand Krishnan', type: 'discharge' },
      { date: '2026-03-28', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-10', event: 'Query: Missing discharge summary', user: 'Star Health Insurance', type: 'followup' },
      { date: '2026-04-18', event: 'Partial Approval ₹2.98L issued', user: 'Star Health Insurance', type: 'approval' },
      { date: '2026-05-07', event: 'Follow-up #4: No settlement', user: 'AR Manager', type: 'followup' },
      { date: '2026-05-16', event: 'Escalated to Insurance Ombudsman', user: 'Claims Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00802',
    patientName: 'Meera Nair',
    uhid: 'HC-004189',
    invoiceNo: 'INV-2026-01802',
    arEntryNo: 'AR-2026-00702',
    tpa: 'HDFC ERGO Health',
    claimType: 'CASHLESS',
    department: 'Orthopedics',
    doctor: 'Dr. Suresh Nair',
    branch: 'North Wing',
    diagnosis: 'Bilateral Knee Replacement',
    admissionDate: '2026-03-18',
    dischargeDate: '2026-03-25',
    claimSubmitDate: '2026-03-26',
    claimAmount: 512000,
    approvedAmount: 512000,
    deniedAmount: 0,
    outstandingAmount: 512000,
    settledAmount: 0,
    agingBucket: 'days61',
    agingDays: 55,
    followUpCount: 6,
    lastFollowUp: '2026-05-17',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'AWAITING_SETTLEMENT',
    recoveryProbability: 78,
    riskLevel: 'HIGH',
    denialReason: null,
    status: 'APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-17',
    timeline: [
      { date: '2026-03-18', event: 'Patient Admitted', user: 'Ortho OPD', type: 'admission' },
      { date: '2026-03-20', event: 'Preauth Approved — ₹5.12L', user: 'HDFC ERGO Health', type: 'approval' },
      { date: '2026-03-25', event: 'Patient Discharged', user: 'Dr. Suresh Nair', type: 'discharge' },
      { date: '2026-03-26', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-08', event: 'Claim Approved — ₹5.12L', user: 'HDFC ERGO Health', type: 'approval' },
      { date: '2026-04-22', event: 'Follow-up #3: Settlement pending', user: 'AR Team', type: 'followup' },
      { date: '2026-05-08', event: 'Follow-up #5: Escalation', user: 'AR Manager', type: 'followup' },
      { date: '2026-05-17', event: 'Follow-up #6: Legal notice consideration', user: 'Claims Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00803',
    patientName: 'Anitha Verma',
    uhid: 'HC-003824',
    invoiceNo: 'INV-2026-01803',
    arEntryNo: 'AR-2026-00703',
    tpa: 'CGHS',
    claimType: 'CGHS',
    department: 'Oncology',
    doctor: 'Dr. Kavita Iyer',
    branch: 'Specialty Center',
    diagnosis: 'Breast Cancer Chemotherapy Cycle 4',
    admissionDate: '2026-03-15',
    dischargeDate: '2026-03-22',
    claimSubmitDate: '2026-03-25',
    claimAmount: 892000,
    approvedAmount: 756000,
    deniedAmount: 136000,
    outstandingAmount: 420000,
    settledAmount: 336000,
    agingBucket: 'days61',
    agingDays: 56,
    followUpCount: 5,
    lastFollowUp: '2026-05-14',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PARTIAL',
    workflowStatus: 'PARTIAL_SETTLEMENT',
    recoveryProbability: 69,
    riskLevel: 'HIGH',
    denialReason: 'Exceeded Package Limit',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-14',
    timeline: [
      { date: '2026-03-15', event: 'Patient Admitted', user: 'Oncology OPD', type: 'admission' },
      { date: '2026-03-22', event: 'Patient Discharged', user: 'Dr. Kavita Iyer', type: 'discharge' },
      { date: '2026-03-25', event: 'Claim Submitted to CGHS', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-10', event: 'Partial Approval ₹7.56L issued', user: 'CGHS Office', type: 'approval' },
      { date: '2026-04-25', event: 'First instalment ₹3.36L received', user: 'Finance', type: 'approval' },
      { date: '2026-05-14', event: 'Follow-up #5: Balance ₹4.20L pending', user: 'AR Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00804',
    patientName: 'Vivek Malhotra',
    uhid: 'HC-003781',
    invoiceNo: 'INV-2026-01804',
    arEntryNo: 'AR-2026-00704',
    tpa: 'MD India TPA',
    claimType: 'REIMBURSEMENT',
    department: 'Neurology',
    doctor: 'Dr. Rajiv Menon',
    branch: 'East Block',
    diagnosis: 'Brain Tumour — Craniotomy',
    admissionDate: '2026-03-12',
    dischargeDate: '2026-03-20',
    claimSubmitDate: '2026-03-22',
    claimAmount: 1240000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 1240000,
    settledAmount: 0,
    agingBucket: 'days61',
    agingDays: 59,
    followUpCount: 6,
    lastFollowUp: '2026-05-18',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 58,
    riskLevel: 'HIGH',
    denialReason: null,
    status: 'UNDER_REVIEW',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-03-12', event: 'Patient Admitted', user: 'Neurology OPD', type: 'admission' },
      { date: '2026-03-20', event: 'Patient Discharged', user: 'Dr. Rajiv Menon', type: 'discharge' },
      { date: '2026-03-22', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-05', event: 'Additional investigation records requested', user: 'MD India TPA', type: 'followup' },
      { date: '2026-04-15', event: 'Documents uploaded', user: 'Claims Team', type: 'followup' },
      { date: '2026-05-01', event: 'Follow-up #4: Still under review', user: 'AR Manager', type: 'followup' },
      { date: '2026-05-18', event: 'Escalated to TPA Grievance Cell', user: 'Claims Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00805',
    patientName: 'Lakshmi Venkataraman',
    uhid: 'HC-003726',
    invoiceNo: 'INV-2026-01805',
    arEntryNo: 'AR-2026-00705',
    tpa: 'Bajaj Allianz Health',
    claimType: 'CORPORATE',
    department: 'Gastroenterology',
    doctor: 'Dr. Rajeev Gupta',
    branch: 'South Clinic',
    diagnosis: 'Liver Cirrhosis — Complications',
    admissionDate: '2026-03-10',
    dischargeDate: '2026-03-22',
    claimSubmitDate: '2026-03-24',
    claimAmount: 584000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 584000,
    settledAmount: 0,
    agingBucket: 'days61',
    agingDays: 57,
    followUpCount: 5,
    lastFollowUp: '2026-05-16',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'PENDING_TPA_RESPONSE',
    recoveryProbability: 62,
    riskLevel: 'HIGH',
    denialReason: null,
    status: 'UNDER_REVIEW',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-16',
    timeline: [
      { date: '2026-03-10', event: 'Patient Admitted', user: 'Emergency', type: 'admission' },
      { date: '2026-03-22', event: 'Patient Discharged', user: 'Dr. Rajeev Gupta', type: 'discharge' },
      { date: '2026-03-24', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-08', event: 'Clarification sought from TPA', user: 'Bajaj Allianz Health', type: 'followup' },
      { date: '2026-04-20', event: 'Clarification provided', user: 'Claims Team', type: 'followup' },
      { date: '2026-05-16', event: 'Follow-up #5: Awaiting decision', user: 'AR Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00806',
    patientName: 'Naresh Bhatt',
    uhid: 'HC-003692',
    invoiceNo: 'INV-2026-01806',
    arEntryNo: 'AR-2026-00706',
    tpa: 'United India Insurance',
    claimType: 'TPA',
    department: 'Cardiology',
    doctor: 'Dr. Anand Krishnan',
    branch: 'Cardiac Care Unit',
    diagnosis: 'Congestive Heart Failure — Acute',
    admissionDate: '2026-03-14',
    dischargeDate: '2026-03-21',
    claimSubmitDate: '2026-03-23',
    claimAmount: 421000,
    approvedAmount: 380000,
    deniedAmount: 41000,
    outstandingAmount: 380000,
    settledAmount: 0,
    agingBucket: 'days61',
    agingDays: 58,
    followUpCount: 6,
    lastFollowUp: '2026-05-17',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 61,
    riskLevel: 'HIGH',
    denialReason: 'Pre-existing Condition',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-17',
    timeline: [
      { date: '2026-03-14', event: 'Patient Admitted — CCU', user: 'Emergency', type: 'admission' },
      { date: '2026-03-21', event: 'Patient Discharged', user: 'Dr. Anand Krishnan', type: 'discharge' },
      { date: '2026-03-23', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-07', event: 'Partial Approval ₹3.80L (₹41K pre-existing)', user: 'United India Insurance', type: 'approval' },
      { date: '2026-04-28', event: 'Follow-up #3: Payment not received', user: 'AR Team', type: 'followup' },
      { date: '2026-05-17', event: 'Escalation to TPA nodal officer', user: 'Claims Manager', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00807',
    patientName: 'Sathya Moorthy',
    uhid: 'HC-003641',
    invoiceNo: 'INV-2026-01807',
    arEntryNo: 'AR-2026-00707',
    tpa: 'National Insurance',
    claimType: 'REIMBURSEMENT',
    department: 'Orthopedics',
    doctor: 'Dr. Suresh Nair',
    branch: 'North Wing',
    diagnosis: 'Hip Fracture — ORIF',
    admissionDate: '2026-03-16',
    dischargeDate: '2026-03-25',
    claimSubmitDate: '2026-03-27',
    claimAmount: 392000,
    approvedAmount: 350000,
    deniedAmount: 42000,
    outstandingAmount: 350000,
    settledAmount: 0,
    agingBucket: 'days61',
    agingDays: 54,
    followUpCount: 5,
    lastFollowUp: '2026-05-15',
    followUpStatus: 'IN_PROGRESS',
    settlementStatus: 'PENDING',
    workflowStatus: 'AWAITING_SETTLEMENT',
    recoveryProbability: 66,
    riskLevel: 'HIGH',
    denialReason: 'Incomplete Documentation',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-15',
    timeline: [
      { date: '2026-03-16', event: 'Patient Admitted', user: 'Emergency', type: 'admission' },
      { date: '2026-03-25', event: 'Patient Discharged', user: 'Dr. Suresh Nair', type: 'discharge' },
      { date: '2026-03-27', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-04-12', event: 'Partial Approval ₹3.50L', user: 'National Insurance', type: 'approval' },
      { date: '2026-05-15', event: 'Follow-up #5: Awaiting NEFT', user: 'AR Team', type: 'followup' },
    ],
  },

  // ── 91-180 days (6 records) ───────────────────────────────────────────────
  {
    id: 'CLM-2026-00701',
    patientName: 'Prakash Iyer',
    uhid: 'HC-003941',
    invoiceNo: 'INV-2026-01701',
    arEntryNo: 'AR-2026-00601',
    tpa: 'New India Assurance',
    claimType: 'REIMBURSEMENT',
    department: 'Neurology',
    doctor: 'Dr. Rajiv Menon',
    branch: 'East Block',
    diagnosis: 'Ischemic Stroke',
    admissionDate: '2026-02-15',
    dischargeDate: '2026-02-22',
    claimSubmitDate: '2026-02-25',
    claimAmount: 284000,
    approvedAmount: 0,
    deniedAmount: 284000,
    outstandingAmount: 284000,
    settledAmount: 0,
    agingBucket: 'days91',
    agingDays: 84,
    followUpCount: 8,
    lastFollowUp: '2026-05-18',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'APPEAL_IN_PROGRESS',
    recoveryProbability: 42,
    riskLevel: 'CRITICAL',
    denialReason: 'Pre-existing Condition',
    status: 'DENIED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-02-15', event: 'Emergency Admission — Stroke', user: 'Emergency', type: 'admission' },
      { date: '2026-02-22', event: 'Patient Discharged', user: 'Dr. Rajiv Menon', type: 'discharge' },
      { date: '2026-02-25', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-03-20', event: 'Claim Denied — Pre-existing condition', user: 'New India Assurance', type: 'followup' },
      { date: '2026-03-28', event: 'Appeal Filed', user: 'Claims Manager', type: 'followup' },
      { date: '2026-04-15', event: 'Appeal Under Review', user: 'New India Assurance', type: 'followup' },
      { date: '2026-05-10', event: 'Follow-up #7: Appeal pending', user: 'AR Manager', type: 'followup' },
      { date: '2026-05-18', event: 'Referred to Insurance Ombudsman', user: 'Legal', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00702',
    patientName: 'Shobha Krishnaswamy',
    uhid: 'HC-003876',
    invoiceNo: 'INV-2026-01702',
    arEntryNo: 'AR-2026-00602',
    tpa: 'Star Health Insurance',
    claimType: 'TPA',
    department: 'ICU',
    doctor: 'Dr. Ashok Verma',
    branch: 'Main Campus',
    diagnosis: 'ARDS — Mechanical Ventilation',
    admissionDate: '2026-02-10',
    dischargeDate: '2026-02-24',
    claimSubmitDate: '2026-02-26',
    claimAmount: 1820000,
    approvedAmount: 1640000,
    deniedAmount: 180000,
    outstandingAmount: 1640000,
    settledAmount: 0,
    agingBucket: 'days91',
    agingDays: 83,
    followUpCount: 9,
    lastFollowUp: '2026-05-17',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 48,
    riskLevel: 'CRITICAL',
    denialReason: 'Incomplete Documentation',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-17',
    timeline: [
      { date: '2026-02-10', event: 'Emergency Admission — ICU', user: 'Emergency', type: 'admission' },
      { date: '2026-02-24', event: 'Patient Discharged', user: 'Dr. Ashok Verma', type: 'discharge' },
      { date: '2026-02-26', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-03-18', event: 'Partial Approval ₹16.40L issued', user: 'Star Health Insurance', type: 'approval' },
      { date: '2026-04-01', event: 'Follow-up #3: No payment received', user: 'AR Manager', type: 'followup' },
      { date: '2026-05-17', event: 'Escalated to Insurance CEO', user: 'Director Finance', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00703',
    patientName: 'Suresh Babu Reddy',
    uhid: 'HC-003802',
    invoiceNo: 'INV-2026-01703',
    arEntryNo: 'AR-2026-00603',
    tpa: 'HDFC ERGO Health',
    claimType: 'TPA',
    department: 'Urology',
    doctor: 'Dr. Ashok Verma',
    branch: 'East Block',
    diagnosis: 'Bladder Cancer — Cystectomy',
    admissionDate: '2026-02-01',
    dischargeDate: '2026-02-12',
    claimSubmitDate: '2026-02-14',
    claimAmount: 960000,
    approvedAmount: 840000,
    deniedAmount: 120000,
    outstandingAmount: 840000,
    settledAmount: 0,
    agingBucket: 'days91',
    agingDays: 95,
    followUpCount: 10,
    lastFollowUp: '2026-05-18',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 44,
    riskLevel: 'CRITICAL',
    denialReason: 'Preauthorization Not Obtained',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-02-01', event: 'Patient Admitted', user: 'Urology OPD', type: 'admission' },
      { date: '2026-02-12', event: 'Patient Discharged', user: 'Dr. Ashok Verma', type: 'discharge' },
      { date: '2026-02-14', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-03-08', event: 'Partial Approval ₹8.40L (₹1.20L denied)', user: 'HDFC ERGO Health', type: 'approval' },
      { date: '2026-04-12', event: 'Follow-up #6: Non-responsive TPA', user: 'AR Manager', type: 'followup' },
      { date: '2026-05-18', event: 'Legal notice dispatched', user: 'Legal Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00704',
    patientName: 'Nalini Gopalakrishnan',
    uhid: 'HC-003748',
    invoiceNo: 'INV-2026-01704',
    arEntryNo: 'AR-2026-00604',
    tpa: 'CGHS',
    claimType: 'CGHS',
    department: 'Cardiology',
    doctor: 'Dr. Anand Krishnan',
    branch: 'Cardiac Care Unit',
    diagnosis: 'Valve Replacement — Mitral',
    admissionDate: '2026-01-28',
    dischargeDate: '2026-02-06',
    claimSubmitDate: '2026-02-08',
    claimAmount: 1480000,
    approvedAmount: 1280000,
    deniedAmount: 200000,
    outstandingAmount: 680000,
    settledAmount: 600000,
    agingBucket: 'days91',
    agingDays: 101,
    followUpCount: 11,
    lastFollowUp: '2026-05-19',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PARTIAL',
    workflowStatus: 'PARTIAL_SETTLEMENT',
    recoveryProbability: 55,
    riskLevel: 'CRITICAL',
    denialReason: 'Exceeded Package Limit',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-19',
    timeline: [
      { date: '2026-01-28', event: 'Patient Admitted', user: 'Cardiology OPD', type: 'admission' },
      { date: '2026-02-06', event: 'Patient Discharged', user: 'Dr. Anand Krishnan', type: 'discharge' },
      { date: '2026-02-08', event: 'Claim Submitted to CGHS', user: 'Claims Team', type: 'submission' },
      { date: '2026-03-12', event: 'Partial Approval ₹12.80L issued', user: 'CGHS Office', type: 'approval' },
      { date: '2026-04-02', event: 'First instalment ₹6.00L received', user: 'Finance', type: 'approval' },
      { date: '2026-05-19', event: 'Follow-up #11: Balance ₹6.80L pending', user: 'Director Finance', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00705',
    patientName: 'Balaji Subramaniam',
    uhid: 'HC-003698',
    invoiceNo: 'INV-2026-01705',
    arEntryNo: 'AR-2026-00605',
    tpa: 'Aditya Birla Health',
    claimType: 'CORPORATE',
    department: 'Oncology',
    doctor: 'Dr. Kavita Iyer',
    branch: 'Specialty Center',
    diagnosis: 'Lung Cancer — Lobectomy',
    admissionDate: '2026-01-22',
    dischargeDate: '2026-02-02',
    claimSubmitDate: '2026-02-04',
    claimAmount: 2140000,
    approvedAmount: 1860000,
    deniedAmount: 280000,
    outstandingAmount: 1860000,
    settledAmount: 0,
    agingBucket: 'days91',
    agingDays: 105,
    followUpCount: 12,
    lastFollowUp: '2026-05-18',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 38,
    riskLevel: 'CRITICAL',
    denialReason: 'Incomplete Documentation',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2026-01-22', event: 'Patient Admitted', user: 'Oncology OPD', type: 'admission' },
      { date: '2026-02-02', event: 'Patient Discharged', user: 'Dr. Kavita Iyer', type: 'discharge' },
      { date: '2026-02-04', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-03-01', event: 'Partial Approval ₹18.60L issued', user: 'Aditya Birla Health', type: 'approval' },
      { date: '2026-04-01', event: 'Follow-up #6: Settlement not received', user: 'AR Manager', type: 'followup' },
      { date: '2026-05-18', event: 'Escalated to Insurance CEO', user: 'Director Finance', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00706',
    patientName: 'Thangavel Murugan',
    uhid: 'HC-003642',
    invoiceNo: 'INV-2026-01706',
    arEntryNo: 'AR-2026-00606',
    tpa: 'United India Insurance',
    claimType: 'TPA',
    department: 'Nephrology',
    doctor: 'Dr. Sunitha Rao',
    branch: 'Main Campus',
    diagnosis: 'ESRD — Kidney Transplant',
    admissionDate: '2026-01-15',
    dischargeDate: '2026-01-28',
    claimSubmitDate: '2026-01-30',
    claimAmount: 3240000,
    approvedAmount: 2800000,
    deniedAmount: 440000,
    outstandingAmount: 1400000,
    settledAmount: 1400000,
    agingBucket: 'days91',
    agingDays: 110,
    followUpCount: 14,
    lastFollowUp: '2026-05-17',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PARTIAL',
    workflowStatus: 'PARTIAL_SETTLEMENT',
    recoveryProbability: 47,
    riskLevel: 'CRITICAL',
    denialReason: 'Pre-existing Condition',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-17',
    timeline: [
      { date: '2026-01-15', event: 'Patient Admitted', user: 'Nephrology OPD', type: 'admission' },
      { date: '2026-01-28', event: 'Patient Discharged', user: 'Dr. Sunitha Rao', type: 'discharge' },
      { date: '2026-01-30', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2026-02-25', event: 'Partial Approval ₹28.00L', user: 'United India Insurance', type: 'approval' },
      { date: '2026-03-20', event: 'First instalment ₹14.00L received', user: 'Finance', type: 'approval' },
      { date: '2026-05-17', event: 'Follow-up #14: Balance ₹14.00L critical', user: 'Director Finance', type: 'followup' },
    ],
  },

  // ── >180 days (4 records) ─────────────────────────────────────────────────
  {
    id: 'CLM-2026-00601',
    patientName: 'Krishnamurthy Pillai',
    uhid: 'HC-003412',
    invoiceNo: 'INV-2026-01601',
    arEntryNo: 'AR-2026-00501',
    tpa: 'National Insurance',
    claimType: 'TPA',
    department: 'ICU',
    doctor: 'Dr. Ashok Verma',
    branch: 'Main Campus',
    diagnosis: 'Polytrauma — Road Traffic Accident',
    admissionDate: '2025-10-12',
    dischargeDate: '2025-11-02',
    claimSubmitDate: '2025-11-05',
    claimAmount: 4280000,
    approvedAmount: 3200000,
    deniedAmount: 1080000,
    outstandingAmount: 3200000,
    settledAmount: 0,
    agingBucket: 'days121',
    agingDays: 196,
    followUpCount: 18,
    lastFollowUp: '2026-05-18',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'APPEAL_IN_PROGRESS',
    recoveryProbability: 28,
    riskLevel: 'CRITICAL',
    denialReason: 'Incomplete Documentation',
    status: 'DENIED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2025-10-12', event: 'Emergency Admission — Trauma ICU', user: 'Emergency', type: 'admission' },
      { date: '2025-11-02', event: 'Patient Discharged', user: 'Dr. Ashok Verma', type: 'discharge' },
      { date: '2025-11-05', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2025-12-08', event: 'Claim Denied — Documentation incomplete', user: 'National Insurance', type: 'followup' },
      { date: '2025-12-22', event: 'Appeal Filed', user: 'Claims Manager', type: 'followup' },
      { date: '2026-02-15', event: 'Appeal rejected — second appeal filed', user: 'Legal Team', type: 'followup' },
      { date: '2026-05-18', event: 'IRDAI Complaint lodged', user: 'Director Finance', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00602',
    patientName: 'Radha Krishnan Nair',
    uhid: 'HC-003288',
    invoiceNo: 'INV-2026-01602',
    arEntryNo: 'AR-2026-00502',
    tpa: 'Oriental Insurance',
    claimType: 'REIMBURSEMENT',
    department: 'Cardiology',
    doctor: 'Dr. Anand Krishnan',
    branch: 'Cardiac Care Unit',
    diagnosis: 'Open Heart Surgery — CABG',
    admissionDate: '2025-10-05',
    dischargeDate: '2025-10-18',
    claimSubmitDate: '2025-10-22',
    claimAmount: 2840000,
    approvedAmount: 2400000,
    deniedAmount: 440000,
    outstandingAmount: 1200000,
    settledAmount: 1200000,
    agingBucket: 'days121',
    agingDays: 209,
    followUpCount: 20,
    lastFollowUp: '2026-05-19',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PARTIAL',
    workflowStatus: 'PARTIAL_SETTLEMENT',
    recoveryProbability: 35,
    riskLevel: 'CRITICAL',
    denialReason: 'Exceeded Package Limit',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-19',
    timeline: [
      { date: '2025-10-05', event: 'Patient Admitted — CICU', user: 'Cardiology OPD', type: 'admission' },
      { date: '2025-10-18', event: 'Patient Discharged', user: 'Dr. Anand Krishnan', type: 'discharge' },
      { date: '2025-10-22', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2025-11-28', event: 'Partial Approval ₹24.00L issued', user: 'Oriental Insurance', type: 'approval' },
      { date: '2025-12-20', event: 'First payment ₹12.00L received', user: 'Finance', type: 'approval' },
      { date: '2026-03-10', event: 'Follow-up #12: Balance ₹12.00L critical', user: 'Director Finance', type: 'followup' },
      { date: '2026-05-19', event: 'IRDAI arbitration initiated', user: 'Legal Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00603',
    patientName: 'Chinnaswamy Gounder',
    uhid: 'HC-003154',
    invoiceNo: 'INV-2026-01603',
    arEntryNo: 'AR-2026-00503',
    tpa: 'New India Assurance',
    claimType: 'REIMBURSEMENT',
    department: 'Oncology',
    doctor: 'Dr. Kavita Iyer',
    branch: 'Specialty Center',
    diagnosis: 'Colorectal Cancer — Resection',
    admissionDate: '2025-09-20',
    dischargeDate: '2025-10-05',
    claimSubmitDate: '2025-10-08',
    claimAmount: 1960000,
    approvedAmount: 0,
    deniedAmount: 1960000,
    outstandingAmount: 1960000,
    settledAmount: 0,
    agingBucket: 'days121',
    agingDays: 224,
    followUpCount: 22,
    lastFollowUp: '2026-05-18',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'APPEAL_IN_PROGRESS',
    recoveryProbability: 22,
    riskLevel: 'CRITICAL',
    denialReason: 'Policy Exclusion',
    status: 'DENIED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-18',
    timeline: [
      { date: '2025-09-20', event: 'Patient Admitted', user: 'Oncology OPD', type: 'admission' },
      { date: '2025-10-05', event: 'Patient Discharged', user: 'Dr. Kavita Iyer', type: 'discharge' },
      { date: '2025-10-08', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2025-11-14', event: 'Denied — Policy exclusion (experimental treatment)', user: 'New India Assurance', type: 'followup' },
      { date: '2025-12-01', event: 'Appeal Filed', user: 'Claims Manager', type: 'followup' },
      { date: '2026-01-20', event: 'Appeal rejected', user: 'New India Assurance', type: 'followup' },
      { date: '2026-03-01', event: 'IRDAI complaint filed', user: 'Legal Team', type: 'followup' },
      { date: '2026-05-18', event: 'IRDAI hearing scheduled', user: 'Legal Team', type: 'followup' },
    ],
  },
  {
    id: 'CLM-2026-00604',
    patientName: 'Ammini Kuriakose',
    uhid: 'HC-003021',
    invoiceNo: 'INV-2026-01604',
    arEntryNo: 'AR-2026-00504',
    tpa: 'Star Health Insurance',
    claimType: 'TPA',
    department: 'Neurology',
    doctor: 'Dr. Rajiv Menon',
    branch: 'East Block',
    diagnosis: 'Spinal Cord Injury — Rehabilitation',
    admissionDate: '2025-09-05',
    dischargeDate: '2025-10-10',
    claimSubmitDate: '2025-10-14',
    claimAmount: 1720000,
    approvedAmount: 1200000,
    deniedAmount: 520000,
    outstandingAmount: 1200000,
    settledAmount: 0,
    agingBucket: 'days121',
    agingDays: 218,
    followUpCount: 21,
    lastFollowUp: '2026-05-20',
    followUpStatus: 'ESCALATED',
    settlementStatus: 'PENDING',
    workflowStatus: 'ESCALATED',
    recoveryProbability: 25,
    riskLevel: 'CRITICAL',
    denialReason: 'Pre-existing Condition',
    status: 'PARTIAL_APPROVED',
    glPosted: true,
    reconciled: false,
    lastUpdated: '2026-05-20',
    timeline: [
      { date: '2025-09-05', event: 'Emergency Admission — Trauma', user: 'Emergency', type: 'admission' },
      { date: '2025-10-10', event: 'Patient Discharged to Rehab', user: 'Dr. Rajiv Menon', type: 'discharge' },
      { date: '2025-10-14', event: 'Claim Submitted', user: 'Claims Team', type: 'submission' },
      { date: '2025-11-22', event: 'Partial Approval ₹12.00L (₹5.20L denied)', user: 'Star Health Insurance', type: 'approval' },
      { date: '2026-01-10', event: 'Follow-up #8: No settlement', user: 'AR Manager', type: 'followup' },
      { date: '2026-03-15', event: 'Escalation to Insurance CEO office', user: 'Director Finance', type: 'followup' },
      { date: '2026-05-20', event: 'IRDAI final hearing today', user: 'Legal Team', type: 'followup' },
    ],
  },
];

// ─── Aging Bucket Totals ──────────────────────────────────────────────────────
export const AGING_BUCKET_TOTALS = [
  { key: 'current', label: '0–30 Days',  color: '#10b981', amount: 28640000, count: 421, pct: 24.2 },
  { key: 'days31',  label: '31–60 Days', color: '#f59e0b', amount: 31820000, count: 387, pct: 26.9 },
  { key: 'days61',  label: '61–90 Days', color: '#f97316', amount: 24180000, count: 298, pct: 20.4 },
  { key: 'days91',  label: '91–180 Days',color: '#ef4444', amount: 21640000, count: 267, pct: 18.3 },
  { key: 'days121', label: '>180 Days',  color: '#dc2626', amount: 12140000, count: 143, pct: 10.2 },
];

// ─── TPA Performance Data ─────────────────────────────────────────────────────
export const TPA_PERFORMANCE = [
  { tpa: 'ICICI Lombard',         avgDays: 22, recoveryRate: 96, outstanding: 14820000, denied: 420000,  highRisk: 0, trend: 4.2  },
  { tpa: 'HDFC ERGO Health',      avgDays: 26, recoveryRate: 91, outstanding: 18640000, denied: 840000,  highRisk: 1, trend: 2.8  },
  { tpa: 'Bajaj Allianz Health',  avgDays: 28, recoveryRate: 88, outstanding: 12480000, denied: 620000,  highRisk: 1, trend: 1.4  },
  { tpa: 'Medi Assist TPA',       avgDays: 32, recoveryRate: 84, outstanding: 16240000, denied: 980000,  highRisk: 2, trend: -1.2 },
  { tpa: 'Star Health Insurance', avgDays: 38, recoveryRate: 79, outstanding: 22840000, denied: 1840000, highRisk: 3, trend: -3.4 },
  { tpa: 'New India Assurance',   avgDays: 48, recoveryRate: 74, outstanding: 18420000, denied: 2140000, highRisk: 3, trend: -5.1 },
  { tpa: 'CGHS',                  avgDays: 58, recoveryRate: 68, outstanding: 14260000, denied: 1280000, highRisk: 2, trend: -4.8 },
  { tpa: 'Oriental Insurance',    avgDays: 72, recoveryRate: 58, outstanding: 12840000, denied: 2840000, highRisk: 4, trend: -8.2 },
];

// ─── Department Aging Heatmap ─────────────────────────────────────────────────
export const DEPT_AGING_HEATMAP = [
  { dept: 'Cardiology',    d0_30: 4820, d31_60: 5240, d61_90: 3840, d91_180: 4200, d180plus: 2840 },
  { dept: 'ICU',           d0_30: 3640, d31_60: 4180, d61_90: 4820, d91_180: 5620, d180plus: 3210 },
  { dept: 'Oncology',      d0_30: 2840, d31_60: 3920, d61_90: 3240, d91_180: 2840, d180plus: 1960 },
  { dept: 'Neurology',     d0_30: 2480, d31_60: 2840, d61_90: 2180, d91_180: 2840, d180plus: 1720 },
  { dept: 'Orthopedics',   d0_30: 3120, d31_60: 3480, d61_90: 2640, d91_180: 1840, d180plus: 840  },
  { dept: 'Nephrology',    d0_30: 2840, d31_60: 3180, d61_90: 2480, d91_180: 2180, d180plus: 640  },
  { dept: 'General Surgery',d0_30: 2180, d31_60: 2640, d61_90: 1840, d91_180: 1420, d180plus: 420 },
  { dept: 'Others',        d0_30: 6720, d31_60: 6340, d61_90: 3140, d91_180: 2700, d180plus: 1510 },
];

// ─── Recovery Trend — 7 months ────────────────────────────────────────────────
export const RECOVERY_TREND = [
  { month: 'Nov', recovered: 8240, outstanding: 9820, denied: 1240 },
  { month: 'Dec', recovered: 8640, outstanding: 10240, denied: 1080 },
  { month: 'Jan', recovered: 9120, outstanding: 11420, denied: 980  },
  { month: 'Feb', recovered: 9840, outstanding: 12180, denied: 840  },
  { month: 'Mar', recovered: 10240, outstanding: 12840, denied: 740 },
  { month: 'Apr', recovered: 11480, outstanding: 13640, denied: 620 },
  { month: 'May', recovered: 12140, outstanding: 11842, denied: 743 },
];

// ─── Settlement Forecast — 8 weeks ───────────────────────────────────────────
export const TAR_SETTLEMENT_FORECAST = [
  { week: 'Wk 18', actual: 4820, forecast: null },
  { week: 'Wk 19', actual: 5140, forecast: null },
  { week: 'Wk 20', actual: 4980, forecast: null },
  { week: 'Wk 21', actual: 5320, forecast: null },
  { week: 'Wk 22', actual: null, forecast: 5840 },
  { week: 'Wk 23', actual: null, forecast: 6280 },
  { week: 'Wk 24', actual: null, forecast: 5960 },
  { week: 'Wk 25', actual: null, forecast: 6640 },
];

// ─── AI Insights — Aging specific ────────────────────────────────────────────
export const TAR_AI_INSIGHTS = [
  {
    id: 'tar-ai-001', severity: 'critical',
    title: '4 claims >180 days — write-off risk',
    detail: '4 TPA claims totalling ₹11.88Cr are aged beyond 180 days. National Insurance and New India Assurance show zero response pattern. AI recommends IRDAI escalation immediately.',
    action: 'Escalate to IRDAI',
    metric: '₹11.88Cr at risk',
  },
  {
    id: 'tar-ai-002', severity: 'critical',
    title: '6 TPAs classified as high-risk',
    detail: 'Star Health, New India, Oriental, National, CGHS, and United India show consistently delayed settlements. AI predicts 34% write-off risk if not resolved by June 30.',
    action: 'View high-risk TPAs',
    metric: '6 flagged TPAs',
  },
  {
    id: 'tar-ai-003', severity: 'warning',
    title: '14 claims transitioning to 90-day bucket',
    detail: '14 claims currently in 61-90 day bucket will cross the critical 90-day threshold within 7 days. Immediate escalation will prevent ₹3.2Cr from entering critical aging.',
    action: 'Escalate now',
    metric: '₹3.2Cr at threshold',
  },
  {
    id: 'tar-ai-004', severity: 'warning',
    title: 'CGHS settlement velocity at 34-day average',
    detail: 'CGHS payment cycle is now 34 days above government mandate. AI identifies seasonal pattern — budget cycle delays common in Q1 of fiscal year. Plan cash flow accordingly.',
    action: 'View CGHS claims',
    metric: '34d above target',
  },
  {
    id: 'tar-ai-005', severity: 'info',
    title: 'Recovery forecast: ₹2.57Cr next 30 days',
    detail: 'Based on TPA approval pipeline and seasonal recovery patterns, AI forecasts ₹2.57Cr in TPA settlements over the next 4 weeks. ICICI Lombard and HDFC ERGO lead the pipeline.',
    action: 'View forecast',
    metric: '₹2.57Cr expected',
  },
  {
    id: 'tar-ai-006', severity: 'info',
    title: 'Star Health denial pattern change detected',
    detail: 'Star Health has increased denials for Cardiology ICU cases by 22% this quarter. Pattern matches a known policy amendment from Jan 2026. Recommend pre-emptive documentation upgrades.',
    action: 'Update documentation',
    metric: '22% denial increase',
  },
];

// ─── AI Prompts ───────────────────────────────────────────────────────────────
export const TAR_AI_PROMPTS = [
  'Which claims are closest to write-off?',
  'Show all >180 day overdue claims',
  'Forecast settlement inflow next month',
  'Identify highest recovery probability claims',
  'Show Star Health aging pattern',
  'Which TPAs are non-responsive?',
  'Calculate denial exposure by TPA',
  'Recommend follow-up priority order',
];

// ─── Denial Reasons for TAR ───────────────────────────────────────────────────
export const TAR_DENIAL_REASONS = [
  { reason: 'Incomplete Documentation',   count: 28, amount: 4840000, pct: 32, avoidable: true  },
  { reason: 'Pre-existing Condition',     count: 19, amount: 3620000, pct: 22, avoidable: false },
  { reason: 'Policy Exclusion',           count: 14, amount: 2840000, pct: 19, avoidable: false },
  { reason: 'Exceeded Package Limit',     count: 11, amount: 1980000, pct: 13, avoidable: true  },
  { reason: 'Preauth Not Obtained',       count: 8,  amount: 1240000, pct: 8,  avoidable: true  },
  { reason: 'Duplicate Claim',            count: 4,  amount: 620000,  pct: 3,  avoidable: true  },
  { reason: 'Patient Not Eligible',       count: 2,  amount: 420000,  pct: 2,  avoidable: false },
  { reason: 'Others',                     count: 3,  amount: 370000,  pct: 3,  avoidable: false },
];

// ─── Settlement Pipeline ──────────────────────────────────────────────────────
export const SETTLEMENT_PIPELINE = [
  { tpa: 'ICICI Lombard',         claims: 12, amount: 4820000,  probability: 98, expectedDate: '2026-05-28', status: 'ON_TRACK'  },
  { tpa: 'HDFC ERGO Health',      claims: 18, amount: 6840000,  probability: 91, expectedDate: '2026-06-02', status: 'ON_TRACK'  },
  { tpa: 'Bajaj Allianz Health',  claims: 9,  amount: 3240000,  probability: 84, expectedDate: '2026-06-05', status: 'ON_TRACK'  },
  { tpa: 'Medi Assist TPA',       claims: 14, amount: 4180000,  probability: 76, expectedDate: '2026-06-10', status: 'AT_RISK'   },
  { tpa: 'Star Health Insurance', claims: 22, amount: 8420000,  probability: 62, expectedDate: '2026-06-15', status: 'AT_RISK'   },
  { tpa: 'New India Assurance',   claims: 17, amount: 6240000,  probability: 48, expectedDate: '2026-06-20', status: 'DELAYED'   },
  { tpa: 'CGHS',                  claims: 11, amount: 5640000,  probability: 41, expectedDate: '2026-06-25', status: 'DELAYED'   },
  { tpa: 'Oriental Insurance',    claims: 8,  amount: 3840000,  probability: 32, expectedDate: '2026-06-30', status: 'CRITICAL'  },
];

// ─── Leakage Alerts ───────────────────────────────────────────────────────────
export const TAR_LEAKAGE_ALERTS = [
  {
    id: 'TLK-001', type: 'WRITE_OFF_RISK',
    title: '4 Claims at Write-off Threshold',
    detail: 'CLM-2026-00601, 00602, 00603, 00604 all exceed 180 days. Without IRDAI escalation, write-off is imminent.',
    impact: 11880000, severity: 'critical',
    action: 'Escalate to IRDAI',
  },
  {
    id: 'TLK-002', type: 'DELAYED_SETTLEMENT',
    title: 'Oriental Insurance — 8 Claims Stalled',
    detail: '8 approved claims (avg 76 days approved) from Oriental Insurance have not been settled. Recovery at risk.',
    impact: 3840000, severity: 'critical',
    action: 'Legal Notice',
  },
  {
    id: 'TLK-003', type: 'APPROACHING_THRESHOLD',
    title: '14 Claims Crossing 90-Day Line',
    detail: '14 claims in the 61-90 day bucket will turn critical within 7 days. Immediate follow-up required.',
    impact: 8420000, severity: 'warning',
    action: 'Bulk Follow-up',
  },
  {
    id: 'TLK-004', type: 'APPEAL_PENDING',
    title: '3 Denial Appeals Inactive >60 Days',
    detail: 'Three formal appeals filed over 60 days ago have no TPA response. IRDAI filing is the next step.',
    impact: 5860000, severity: 'warning',
    action: 'File IRDAI',
  },
  {
    id: 'TLK-005', type: 'DOCS_MISSING',
    title: '6 Claims Unsubmitted — Documentation Gaps',
    detail: '6 claims are stuck in documentation-pending state for >15 days. Each day increases denial risk.',
    impact: 2140000, severity: 'warning',
    action: 'Upload Docs',
  },
  {
    id: 'TLK-006', type: 'RECONCILIATION_GAP',
    title: '3 Settled Claims Not Reconciled in GL',
    detail: 'Three TPA settlements received last month have not been reconciled in AR/GL. Cash is in limbo.',
    impact: 1820000, severity: 'info',
    action: 'Reconcile Now',
  },
];
