'use strict';

const Decimal = require('decimal.js');
const { v4: uuidv4 } = require('uuid');
const { sequelize } = require('../../../config/database');
const accountingEngine = require('../../../shared/accounting-engine');
const { eventBus } = require('../../../shared/events/eventBus');
const { EVENT_TYPES } = require('../../../shared/events/eventTypes');

/**
 * Doctor Revenue Sharing Engine
 *
 * Supports three formula types:
 * 1. PERCENTAGE — Fixed % of revenue generated by doctor
 * 2. SLAB — Progressive slabs (like income tax)
 * 3. PROCEDURE — Per-procedure fixed/percentage fee
 *
 * Example SLAB formula:
 *   0 - 5,00,000    → 20%
 *   5,00,001 - 15,00,000 → 25%
 *   15,00,001+      → 30%
 */

/**
 * Calculate revenue share for a doctor for a period.
 *
 * @param {Object} doctor - Doctor record with formula
 * @param {Array} transactions - Revenue transactions by this doctor
 * @param {Object} formula - Revenue sharing formula
 * @returns {Object} Payout calculation
 */
function calculateRevenueShare(doctor, transactions, formula) {
  const totalRevenue = transactions.reduce(
    (sum, tx) => sum.plus(new Decimal(tx.amount || 0)),
    new Decimal(0)
  );

  let payoutAmount = new Decimal(0);
  let breakdown = [];

  switch (formula.type) {
    case 'PERCENTAGE': {
      const rate = new Decimal(formula.percentage || 0);
      payoutAmount = totalRevenue.times(rate).dividedBy(100);
      breakdown = [{ description: `${formula.percentage}% of revenue`, revenue: totalRevenue.toFixed(2), rate: formula.percentage, amount: payoutAmount.toFixed(2) }];
      break;
    }

    case 'SLAB': {
      const slabs = formula.slabs || [];
      let remaining = totalRevenue;
      let processed = new Decimal(0);

      for (const slab of slabs) {
        const slabMin = new Decimal(slab.from || 0);
        const slabMax = slab.to ? new Decimal(slab.to) : null;
        const rate = new Decimal(slab.percentage || 0);

        if (remaining.isZero()) break;

        const slabCap = slabMax ? slabMax.minus(slabMin) : remaining;
        const applicableAmount = remaining.greaterThan(slabCap) ? slabCap : remaining;
        const slabPayout = applicableAmount.times(rate).dividedBy(100);

        payoutAmount = payoutAmount.plus(slabPayout);
        remaining = remaining.minus(applicableAmount);
        processed = processed.plus(applicableAmount);

        breakdown.push({
          slab: `${slab.from} - ${slab.to || 'above'}`,
          revenue: applicableAmount.toFixed(2),
          rate: slab.percentage,
          amount: slabPayout.toFixed(2),
        });
      }
      break;
    }

    case 'PROCEDURE': {
      const procedureMap = (formula.procedures || []).reduce((m, p) => {
        m[p.procedureCode] = p;
        return m;
      }, {});

      for (const tx of transactions) {
        const procedureFormula = procedureMap[tx.procedureCode];
        if (!procedureFormula) continue;

        let txPayout;
        if (procedureFormula.type === 'FIXED') {
          txPayout = new Decimal(procedureFormula.amount || 0).times(tx.quantity || 1);
        } else {
          txPayout = new Decimal(tx.amount || 0).times(procedureFormula.percentage || 0).dividedBy(100);
        }

        payoutAmount = payoutAmount.plus(txPayout);
        breakdown.push({
          procedure: tx.procedureName,
          code: tx.procedureCode,
          revenue: tx.amount,
          rate: procedureFormula.percentage || procedureFormula.amount,
          amount: txPayout.toFixed(2),
        });
      }
      break;
    }
  }

  // Apply minimum guarantee if configured
  if (formula.minimumGuarantee && payoutAmount.lessThan(formula.minimumGuarantee)) {
    const minimumAmount = new Decimal(formula.minimumGuarantee);
    breakdown.push({
      description: 'Minimum guarantee applied',
      original: payoutAmount.toFixed(2),
      minimum: minimumAmount.toFixed(2),
    });
    payoutAmount = minimumAmount;
  }

  // Apply maximum cap if configured
  if (formula.maximumCap && payoutAmount.greaterThan(formula.maximumCap)) {
    const capAmount = new Decimal(formula.maximumCap);
    breakdown.push({ description: 'Maximum cap applied', original: payoutAmount.toFixed(2), cap: capAmount.toFixed(2) });
    payoutAmount = capAmount;
  }

  // Calculate TDS on doctor fees (Section 194J)
  const { calculateTDS } = require('../../../shared/utils/taxCalculator');
  const tdsCalc = calculateTDS({ section: '194J', amount: payoutAmount, hasPAN: doctor.hasPAN !== false });

  return {
    doctorId: doctor.id,
    doctorName: doctor.name,
    formulaType: formula.type,
    totalRevenue: totalRevenue.toFixed(2),
    grossPayout: payoutAmount.toFixed(2),
    tdsDeducted: tdsCalc.tdsAmount,
    tdsRate: tdsCalc.tdsRate,
    netPayout: tdsCalc.netPayable,
    breakdown,
    transactionCount: transactions.length,
  };
}

/**
 * Run doctor payouts for a period.
 */
async function runDoctorPayouts({ tenantId, year, month, fiscalYearId, initiatedBy }) {
  const [existingRun] = await sequelize.query(
    `SELECT id FROM payout_runs WHERE tenant_id = :tenantId AND year = :year AND month = :month`,
    { replacements: { tenantId, year, month }, type: sequelize.QueryTypes.SELECT }
  );

  if (existingRun) throw Object.assign(new Error(`Payout run already exists for ${year}-${month}`), { statusCode: 409 });

  // Get all doctors with active formulas
  const doctors = await sequelize.query(
    `SELECT d.*, rsf.formula_config, rsf.formula_type
     FROM doctors d
     LEFT JOIN revenue_share_formulas rsf ON rsf.doctor_id = d.id AND rsf.is_active = true
     WHERE d.tenant_id = :tenantId AND d.is_active = true`,
    { replacements: { tenantId }, type: sequelize.QueryTypes.SELECT }
  );

  const runId = uuidv4();
  await sequelize.query(
    `INSERT INTO payout_runs (id, tenant_id, year, month, status, total_doctors,
     initiated_by, fiscal_year_id, created_at, updated_at)
     VALUES (:id, :tenantId, :year, :month, 'PROCESSING', :totalDoctors, :initiatedBy, :fiscalYearId, NOW(), NOW())`,
    { replacements: { id: runId, tenantId, year, month, totalDoctors: doctors.length, initiatedBy, fiscalYearId } }
  );

  const payoutDetails = [];
  let totalGrossPayout = new Decimal(0);
  let totalTDS = new Decimal(0);
  let totalNetPayout = new Decimal(0);

  for (const doctor of doctors) {
    if (!doctor.formula_config) continue;

    // Get revenue for this doctor in this month
    const transactions = await sequelize.query(
      `SELECT pi.net_amount as amount, ili.service_code as procedure_code,
              ili.service_name as procedure_name, 1 as quantity
       FROM patient_invoices pi
       JOIN invoice_line_items ili ON ili.invoice_id = pi.id
       WHERE pi.tenant_id = :tenantId
         AND pi.treating_doctor_id = :doctorId
         AND pi.status = 'FINALIZED'
         AND EXTRACT(YEAR FROM pi.invoice_date) = :year
         AND EXTRACT(MONTH FROM pi.invoice_date) = :month`,
      { replacements: { tenantId, doctorId: doctor.id, year, month }, type: sequelize.QueryTypes.SELECT }
    );

    const formula = {
      type: doctor.formula_type,
      ...JSON.parse(doctor.formula_config || '{}'),
    };

    const calc = calculateRevenueShare(doctor, transactions, formula);

    const detailId = uuidv4();
    await sequelize.query(
      `INSERT INTO payout_details (id, tenant_id, run_id, doctor_id, year, month,
       total_revenue, gross_payout, tds_amount, tds_rate, net_payout,
       formula_type, breakdown, created_at, updated_at)
       VALUES (:id, :tenantId, :runId, :doctorId, :year, :month,
       :totalRevenue, :grossPayout, :tdsAmount, :tdsRate, :netPayout,
       :formulaType, :breakdown, NOW(), NOW())`,
      {
        replacements: {
          id: detailId, tenantId, runId, doctorId: doctor.id, year, month,
          totalRevenue: calc.totalRevenue,
          grossPayout: calc.grossPayout,
          tdsAmount: calc.tdsDeducted,
          tdsRate: calc.tdsRate,
          netPayout: calc.netPayout,
          formulaType: calc.formulaType,
          breakdown: JSON.stringify(calc.breakdown),
        },
      }
    );

    totalGrossPayout = totalGrossPayout.plus(calc.grossPayout);
    totalTDS = totalTDS.plus(calc.tdsDeducted);
    totalNetPayout = totalNetPayout.plus(calc.netPayout);
    payoutDetails.push({ detailId, ...calc });
  }

  await sequelize.query(
    `UPDATE payout_runs SET status = 'CALCULATED', total_gross_payout = :totalGross,
     total_tds = :totalTDS, total_net_payout = :totalNet, updated_at = NOW()
     WHERE id = :runId`,
    {
      replacements: {
        totalGross: totalGrossPayout.toFixed(2), totalTDS: totalTDS.toFixed(2),
        totalNet: totalNetPayout.toFixed(2), runId,
      },
    }
  );

  // Post GL journal: DR Doctor Payout Expense, DR TDS Payable (if any), CR Doctor Payable
  try {
    const getOrCreateAccount = async (code, name, type) => {
      const [existing] = await sequelize.query(
        `SELECT id FROM accounts WHERE code = :code AND tenant_id = :tenantId`,
        { replacements: { code, tenantId }, type: sequelize.QueryTypes.SELECT }
      );
      if (existing) return existing.id;
      const { v4: uuidv4 } = require('uuid');
      const id = uuidv4();
      await sequelize.query(
        `INSERT INTO accounts (id, tenant_id, code, name, type, is_group, is_active, currency, current_balance, created_at, updated_at)
         VALUES (:id, :tenantId, :code, :name, :type, false, true, 'INR', 0, NOW(), NOW())`,
        { replacements: { id, tenantId, code, name, type } }
      );
      return id;
    };

    const [expenseAccId, payableAccId, tdsAccId] = await Promise.all([
      getOrCreateAccount('5100', 'Doctor Payout Expense', 'EXPENSE'),
      getOrCreateAccount('2100', 'Doctor Payable', 'LIABILITY'),
      getOrCreateAccount('2330', 'TDS Payable - Section 194J', 'LIABILITY'),
    ]);

    const gross = parseFloat(totalGrossPayout.toFixed(2));
    const tds   = parseFloat(totalTDS.toFixed(2));
    const lines = [
      { accountId: expenseAccId, debit: gross, credit: 0,   narration: 'Doctor Payout Expense' },
      { accountId: payableAccId, debit: 0,     credit: gross - tds, narration: 'Doctor Payable (net)' },
    ];
    if (tds > 0) {
      lines.push({ accountId: tdsAccId, debit: 0, credit: tds, narration: 'TDS Deducted u/s 194J' });
    }

    await accountingEngine.postJournalEntry({
      tenantId,
      voucherType: 'JOURNAL',
      date: new Date(year, month - 1, 28),
      fiscalYearId,
      narration: `Doctor Payout: ${year}-${String(month).padStart(2, '0')}`,
      reference: `DPAYOUT-${year}-${String(month).padStart(2, '0')}`,
      sourceModule: 'doctor-payout',
      sourceId: runId,
      postedBy: initiatedBy,
      lines,
    });
  } catch (err) {
    const logger = require('../../../shared/utils/logger');
    logger.error('[DoctorPayout] GL journal post failed', { runId, error: err.message });
  }

  eventBus.publish(EVENT_TYPES.DOCTOR_PAYOUT.PAYOUT_CALCULATED, {
    runId, tenantId, year, month, totalGrossPayout: totalGrossPayout.toFixed(2),
  });

  return {
    runId, year, month, doctorCount: doctors.length,
    totalGrossPayout: totalGrossPayout.toFixed(2),
    totalTDS: totalTDS.toFixed(2),
    totalNetPayout: totalNetPayout.toFixed(2),
    payoutDetails,
  };
}

module.exports = {
  calculateRevenueShare,
  runDoctorPayouts,
};
