// ─── Insurance Claims Dashboard — Constants & Mock Data ──────────────────────

export const fmtINR = (n) => {
  if (n == null) return '—';
  const abs = Math.abs(n);
  const pfx = n < 0 ? '-' : '';
  if (abs >= 10000000) return `${pfx}₹${(abs / 10000000).toFixed(2)}Cr`;
  if (abs >= 100000)   return `${pfx}₹${(abs / 100000).toFixed(2)}L`;
  if (abs >= 1000)     return `${pfx}₹${(abs / 1000).toFixed(1)}K`;
  return `${pfx}₹${abs.toFixed(0)}`;
};

export const fmtINRFull = (n) => {
  if (n == null) return '—';
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n);
};

export const fmtDate = (d) => {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

export const fmtDateTime = (d) => {
  if (!d) return '—';
  return new Date(d).toLocaleString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' });
};

// ─── Claim Status ─────────────────────────────────────────────────────────────
export const CLAIM_STATUSES = {
  DRAFT:            { label: 'Draft',              bg: 'bg-slate-100 dark:bg-slate-800',      text: 'text-slate-600 dark:text-slate-300',   dot: '#94a3b8' },
  PENDING_DOCS:     { label: 'Pending Docs',       bg: 'bg-amber-100 dark:bg-amber-900/30',   text: 'text-amber-700 dark:text-amber-400',   dot: '#f59e0b' },
  SUBMITTED:        { label: 'Submitted',          bg: 'bg-blue-100 dark:bg-blue-900/30',     text: 'text-blue-700 dark:text-blue-400',     dot: '#3b82f6' },
  UNDER_REVIEW:     { label: 'Under Review',       bg: 'bg-violet-100 dark:bg-violet-900/30', text: 'text-violet-700 dark:text-violet-400', dot: '#8b5cf6' },
  APPROVED:         { label: 'Approved',           bg: 'bg-emerald-100 dark:bg-emerald-900/30',text: 'text-emerald-700 dark:text-emerald-400',dot: '#10b981' },
  PARTIAL_APPROVED: { label: 'Partial Approved',   bg: 'bg-teal-100 dark:bg-teal-900/30',     text: 'text-teal-700 dark:text-teal-400',     dot: '#14b8a6' },
  DENIED:           { label: 'Denied',             bg: 'bg-red-100 dark:bg-red-900/30',       text: 'text-red-700 dark:text-red-400',       dot: '#ef4444' },
  RESUBMITTED:      { label: 'Resubmitted',        bg: 'bg-cyan-100 dark:bg-cyan-900/30',     text: 'text-cyan-700 dark:text-cyan-400',     dot: '#06b6d4' },
  SETTLED:          { label: 'Settled',            bg: 'bg-green-100 dark:bg-green-900/30',   text: 'text-green-700 dark:text-green-400',   dot: '#22c55e' },
  RECONCILED:       { label: 'Reconciled',         bg: 'bg-indigo-100 dark:bg-indigo-900/30', text: 'text-indigo-700 dark:text-indigo-400', dot: '#6366f1' },
  CLOSED:           { label: 'Closed',             bg: 'bg-gray-100 dark:bg-gray-800',        text: 'text-gray-500 dark:text-gray-400',     dot: '#6b7280' },
};

// ─── Claim Types ──────────────────────────────────────────────────────────────
export const CLAIM_TYPES = {
  TPA:          { label: 'TPA',             color: '#6366f1', lightBg: 'bg-indigo-50 dark:bg-indigo-900/20', text: 'text-indigo-700 dark:text-indigo-400' },
  CORPORATE:    { label: 'Corporate',       color: '#3b82f6', lightBg: 'bg-blue-50 dark:bg-blue-900/20',    text: 'text-blue-700 dark:text-blue-400'    },
  GOVERNMENT:   { label: 'Government',      color: '#10b981', lightBg: 'bg-emerald-50 dark:bg-emerald-900/20',text: 'text-emerald-700 dark:text-emerald-400'},
  CASHLESS:     { label: 'Cashless',        color: '#8b5cf6', lightBg: 'bg-violet-50 dark:bg-violet-900/20',text: 'text-violet-700 dark:text-violet-400' },
  REIMBURSEMENT:{ label: 'Reimbursement',   color: '#f59e0b', lightBg: 'bg-amber-50 dark:bg-amber-900/20',  text: 'text-amber-700 dark:text-amber-400'  },
  PACKAGE:      { label: 'Package Based',   color: '#06b6d4', lightBg: 'bg-cyan-50 dark:bg-cyan-900/20',    text: 'text-cyan-700 dark:text-cyan-400'    },
  ECHS:         { label: 'ECHS',            color: '#0d9488', lightBg: 'bg-teal-50 dark:bg-teal-900/20',    text: 'text-teal-700 dark:text-teal-400'    },
  CGHS:         { label: 'CGHS',            color: '#16a34a', lightBg: 'bg-green-50 dark:bg-green-900/20',  text: 'text-green-700 dark:text-green-400'  },
};

// ─── Risk Levels ──────────────────────────────────────────────────────────────
export const RISK_LEVELS = {
  LOW:      { label: 'Low',      color: '#10b981', bg: 'bg-emerald-100 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-400' },
  MEDIUM:   { label: 'Medium',   color: '#f59e0b', bg: 'bg-amber-100 dark:bg-amber-900/30',    text: 'text-amber-700 dark:text-amber-400'    },
  HIGH:     { label: 'High',     color: '#f97316', bg: 'bg-orange-100 dark:bg-orange-900/30',  text: 'text-orange-700 dark:text-orange-400'  },
  CRITICAL: { label: 'Critical', color: '#ef4444', bg: 'bg-red-100 dark:bg-red-900/30',        text: 'text-red-700 dark:text-red-400'        },
};

// ─── Aging Buckets ────────────────────────────────────────────────────────────
export const AGING_BUCKETS = [
  { key: 'current', label: '0–30 days',  color: '#10b981', darkColor: '#34d399' },
  { key: 'days31',  label: '31–60 days', color: '#f59e0b', darkColor: '#fbbf24' },
  { key: 'days61',  label: '61–90 days', color: '#f97316', darkColor: '#fb923c' },
  { key: 'days91',  label: '91–120 days',color: '#ef4444', darkColor: '#f87171' },
  { key: 'days121', label: '120+ days',  color: '#7f1d1d', darkColor: '#dc2626' },
];

// ─── Denial Reasons ───────────────────────────────────────────────────────────
export const DENIAL_REASONS = [
  'Missing Discharge Summary',
  'Policy Exclusion',
  'Pre-existing Condition',
  'Incomplete Documentation',
  'Exceeded Package Limit',
  'Investigation Not Covered',
  'Duplicate Claim',
  'Patient Not Eligible',
  'Preauthorization Not Obtained',
  'Delay in Submission',
  'Non-Network Hospital Charges',
  'Experimental Treatment',
  'Cosmetic Procedure',
  'Waiting Period Not Met',
];

// ─── Insurance / TPA List ─────────────────────────────────────────────────────
export const INSURANCE_TPAS = [
  'Star Health Insurance',
  'HDFC ERGO Health',
  'ICICI Lombard',
  'New India Assurance',
  'United India Insurance',
  'Oriental Insurance',
  'National Insurance',
  'Bajaj Allianz Health',
  'Aditya Birla Health',
  'Medi Assist TPA',
  'Paramount TPA',
  'Vipul Medcorp TPA',
  'Health India TPA',
  'MD India TPA',
  'CGHS',
  'ECHS Board',
  'Infosys Employee Health',
  'Wipro EHI',
  'HCL Health Plan',
];

export const DEPARTMENTS = [
  'Cardiology','ICU','OT','General Surgery','Neurology',
  'Oncology','Orthopedics','Pediatrics','Radiology','Emergency',
  'Nephrology','Psychiatry','Gynecology','Urology','Gastroenterology',
];

export const DOCTORS = [
  'Dr. Anand Krishnan','Dr. Meena Pillai','Dr. Suresh Nair','Dr. Priya Sharma',
  'Dr. Rajiv Menon','Dr. Kavita Iyer','Dr. Ashok Verma','Dr. Sunitha Rao',
  'Dr. Rajeev Gupta','Dr. Lakshmi Devi',
];

export const BRANCHES = ['Main Campus','North Wing','East Block','South Clinic','Specialty Center','Cardiac Care Unit'];

// ─── KPI Config ───────────────────────────────────────────────────────────────
export const IC_KPI_CONFIG = [
  {
    id: 'totalClaims',       label: 'Total Claims Value',         value: 84250000,   format: 'lakh',
    trend: 12.4,  trendLabel: 'vs last month',  color: '#6366f1', icon: 'Shield',        aiFlag: false,
    sub: '1,247 claims',
  },
  {
    id: 'pendingClaims',     label: 'Pending Submission',         value: 18640000,   format: 'lakh',
    trend: -6.2,  trendLabel: 'vs last month',  color: '#f59e0b', icon: 'Clock',         aiFlag: true,
    sub: '312 claims',
  },
  {
    id: 'approvedClaims',    label: 'Approved Claims',            value: 42180000,   format: 'lakh',
    trend: 8.7,   trendLabel: 'vs last month',  color: '#10b981', icon: 'CheckCircle2',  aiFlag: false,
    sub: '687 claims',
  },
  {
    id: 'deniedClaims',      label: 'Denied / Rejected',          value: 7430000,    format: 'lakh',
    trend: -14.1, trendLabel: 'vs last month',  color: '#ef4444', icon: 'XCircle',       aiFlag: true,
    sub: '89 claims',
  },
  {
    id: 'partialSettlement', label: 'Partial Settlements',        value: 5210000,    format: 'lakh',
    trend: 3.2,   trendLabel: 'vs last month',  color: '#f97316', icon: 'SplitSquareH',  aiFlag: false,
    sub: '74 claims',
  },
  {
    id: 'agingExposure',     label: 'Aging Exposure (90d+)',      value: 11820000,   format: 'lakh',
    trend: -9.4,  trendLabel: 'vs last month',  color: '#dc2626', icon: 'AlertOctagon',  aiFlag: true,
    sub: '143 claims',
  },
  {
    id: 'recoveryRate',      label: 'Recovery Rate',              value: 87.3,       format: 'pct',
    trend: 2.1,   trendLabel: 'vs last quarter',color: '#0d9488', icon: 'TrendingUp',    aiFlag: false,
    sub: 'vs 85.2% target',
  },
  {
    id: 'avgSettlementDays', label: 'Avg Settlement Days',        value: 34,         format: 'num',
    trend: -8,    trendLabel: 'days vs last month', color: '#8b5cf6', icon: 'CalendarClock', aiFlag: true,
    sub: 'Target: 30 days',
  },
  {
    id: 'leakageAlerts',     label: 'Revenue Leakage Alerts',     value: 2840000,    format: 'lakh',
    trend: -18.6, trendLabel: 'vs last month',  color: '#be185d', icon: 'Zap',           aiFlag: true,
    sub: '23 active alerts',
  },
  {
    id: 'highRiskClaims',    label: 'High Risk Claims',           value: 38,         format: 'num',
    trend: -5,    trendLabel: 'vs last week',   color: '#ea580c', icon: 'AlertTriangle',  aiFlag: true,
    sub: 'AI denial risk >70%',
  },
];

// ─── Lifecycle Funnel Data ────────────────────────────────────────────────────
export const LIFECYCLE_FUNNEL = [
  { stage: 'Preauth Requested',   count: 1380, amount: 94200000, color: '#6366f1' },
  { stage: 'Preauth Approved',    count: 1247, amount: 84250000, color: '#8b5cf6' },
  { stage: 'Claims Submitted',    count: 1089, amount: 76180000, color: '#3b82f6' },
  { stage: 'Under TPA Review',    count: 742,  amount: 52840000, color: '#06b6d4' },
  { stage: 'Approved by TPA',     count: 687,  amount: 42180000, color: '#10b981' },
  { stage: 'Settlement Pending',  count: 298,  amount: 21640000, color: '#f59e0b' },
  { stage: 'Settled & Reconciled',count: 201,  amount: 14820000, color: '#22c55e' },
];

// ─── Claims Trend Data ────────────────────────────────────────────────────────
export const CLAIMS_TREND = [
  { month: 'Nov',  submitted: 87,  approved: 72,  denied: 15, settled: 68, value: 5820 },
  { month: 'Dec',  submitted: 94,  approved: 78,  denied: 16, settled: 74, value: 6240 },
  { month: 'Jan',  submitted: 108, approved: 89,  denied: 19, settled: 81, value: 7180 },
  { month: 'Feb',  submitted: 116, approved: 97,  denied: 19, settled: 89, value: 7640 },
  { month: 'Mar',  submitted: 129, approved: 108, denied: 21, settled: 96, value: 8420 },
  { month: 'Apr',  submitted: 143, approved: 118, denied: 25, settled: 104,value: 9180 },
  { month: 'May',  submitted: 158, approved: 131, denied: 27, settled: 112,value: 10240},
];

// ─── Denial Breakdown ─────────────────────────────────────────────────────────
export const DENIAL_BREAKDOWN = [
  { reason: 'Missing Documentation',  count: 28, amount: 2140000, pct: 31 },
  { reason: 'Policy Exclusion',       count: 19, amount: 1620000, pct: 21 },
  { reason: 'Preauth Not Obtained',   count: 14, amount: 1180000, pct: 16 },
  { reason: 'Exceeded Package Limit', count: 11, amount: 980000,  pct: 12 },
  { reason: 'Pre-existing Condition', count: 9,  amount: 760000,  pct: 10 },
  { reason: 'Delay in Submission',    count: 5,  amount: 420000,  pct: 6  },
  { reason: 'Others',                 count: 3,  amount: 330000,  pct: 4  },
];

// ─── Settlement Forecast ──────────────────────────────────────────────────────
export const SETTLEMENT_FORECAST = [
  { week: 'Wk 21', actual: 4820, forecast: null },
  { week: 'Wk 22', actual: 5140, forecast: null },
  { week: 'Wk 23', actual: 4980, forecast: null },
  { week: 'Wk 24', actual: null, forecast: 5620 },
  { week: 'Wk 25', actual: null, forecast: 6180 },
  { week: 'Wk 26', actual: null, forecast: 5840 },
  { week: 'Wk 27', actual: null, forecast: 6420 },
];

// ─── AI Insights ──────────────────────────────────────────────────────────────
export const AI_INSIGHTS = [
  {
    id: 'ai-001', severity: 'critical',
    title: '38 claims at high denial risk',
    detail: 'AI predicts 38 claims worth ₹4.2Cr have >70% denial probability based on missing documentation patterns and historical TPA behavior.',
    action: 'Review high-risk claims',
    metric: '₹4.2Cr at risk',
  },
  {
    id: 'ai-002', severity: 'warning',
    title: '23 claims approaching 90-day aging',
    detail: 'ICU and Cardiology claims nearing the 90-day escalation threshold. Immediate TPA follow-up recommended to avoid write-offs.',
    action: 'Send TPA escalations',
    metric: '₹2.8Cr exposure',
  },
  {
    id: 'ai-003', severity: 'warning',
    title: 'Star Health denial rate up 14%',
    detail: 'Star Health Insurance has increased denial rate by 14% this month, primarily for Cardiology pre-op investigations. Pattern suggests policy change.',
    action: 'Adjust claim packing',
    metric: '14% denial spike',
  },
  {
    id: 'ai-004', severity: 'info',
    title: 'Settlement forecast: ₹6.18Cr next 30 days',
    detail: 'Based on TPA processing timelines and approved claim pipeline, AI forecasts ₹6.18Cr in settlements over the next 4 weeks.',
    action: 'View forecast details',
    metric: '₹6.18Cr expected',
  },
  {
    id: 'ai-005', severity: 'info',
    title: 'Package leakage in OT billing detected',
    detail: '7 OT claims show charges ₹18,000–₹42,000 below package ceiling. Recommend re-review with clinical team to capture legitimate costs.',
    action: 'Review OT claims',
    metric: '₹1.9L recoverable',
  },
];

export const AI_PROMPTS = [
  'Predict denied claims this week',
  'Show claims with missing documentation',
  'Find high-risk Cardiology claims',
  'Forecast next month settlements',
  'Detect revenue leakage opportunities',
  'Show Star Health pending > 60 days',
  'Recommend recovery priorities',
  'Compare TPA performance',
];

export const AI_MESSAGES_INIT = [
  {
    role: 'ai',
    text: 'Insurance Claims AI ready. I can predict denials, detect revenue leakage, forecast settlements, and recommend recovery actions across your entire TPA portfolio.',
    actions: ['Predict Denials', 'Find Leakage', 'Forecast Settlements'],
  },
];

// ─── Leakage Alerts ───────────────────────────────────────────────────────────
export const LEAKAGE_ALERTS = [
  {
    id: 'LK-001', type: 'MISSING_SUBMISSION',
    title: 'Unsubmitted Claims Detected',
    detail: '14 discharged patients with insurance have no claim submission in the last 10 days.',
    impact: 3840000, severity: 'critical',
    action: 'Submit Now',
    department: 'Multiple',
  },
  {
    id: 'LK-002', type: 'DOCUMENTATION_GAP',
    title: 'Incomplete Documentation — 28 Claims',
    detail: '28 claims are at submission stage but missing discharge summaries or lab reports.',
    impact: 2140000, severity: 'critical',
    action: 'Upload Documents',
    department: 'ICU / OT',
  },
  {
    id: 'LK-003', type: 'UNDERBILLING',
    title: 'OT Package Underbilling',
    detail: '7 OT cases billed below package ceiling. Clinical review may recover ₹1.9L.',
    impact: 190000, severity: 'warning',
    action: 'Review Bills',
    department: 'OT',
  },
  {
    id: 'LK-004', type: 'DELAY_SUBMISSION',
    title: '9 Claims Approaching Submission Deadline',
    detail: '9 claims will breach the 30-day submission window within 72 hours.',
    impact: 4120000, severity: 'critical',
    action: 'Prioritise',
    department: 'Cardiology / ICU',
  },
  {
    id: 'LK-005', type: 'UNRECONCILED',
    title: 'Unreconciled Settlements — 3 TPA Payments',
    detail: '3 TPA settlement cheques received but not linked to AR/GL entries.',
    impact: 1680000, severity: 'warning',
    action: 'Reconcile',
    department: 'Finance',
  },
];

// ─── Mock Claims Data ─────────────────────────────────────────────────────────
export const MOCK_CLAIMS = [
  {
    id: 'CLM-2026-00847',
    patientName: 'Rajesh Kumar Sharma',
    uhid: 'HC-004231',
    invoiceNo: 'INV-2026-01847',
    tpa: 'Star Health Insurance',
    claimType: 'TPA',
    department: 'Cardiology',
    doctor: 'Dr. Anand Krishnan',
    branch: 'Main Campus',
    claimAmount: 348500,
    approvedAmount: 298000,
    deniedAmount: 50500,
    outstandingAmount: 298000,
    status: 'UNDER_REVIEW',
    agingDays: 42,
    submissionDate: '2026-04-08',
    settlementStatus: 'PENDING',
    riskLevel: 'HIGH',
    riskScore: 74,
    workflowStatus: 'Pending TPA Response',
    lastUpdated: '2026-05-18 14:23',
    preAuthNo: 'PA-2026-03421',
    admissionDate: '2026-04-02',
    dischargeDate: '2026-04-08',
    age: 58, gender: 'Male',
    mobile: '9876543210',
    ward: 'CICU – Bed 4',
    diagnosis: 'Acute Myocardial Infarction',
    denialReasons: ['Incomplete Documentation'],
    settlementHistory: [],
    arEntry: 'AR-2026-00421',
    glPosting: 'GL-2026-00847',
    leakage: true,
    leakageNote: 'Discharge summary missing — may lead to denial',
    aiDenialRisk: 74,
    aiRecoveryProb: 68,
    documents: ['Preauth Letter', 'Admission Summary', 'Lab Reports'],
    missingDocs: ['Discharge Summary', 'Treating Doctor Certificate'],
    timeline: [
      { ts: '2026-04-02 09:00', event: 'Patient Admitted', user: 'Reception' },
      { ts: '2026-04-03 11:30', event: 'Preauth Submitted', user: 'TPA Desk' },
      { ts: '2026-04-04 15:45', event: 'Preauth Approved — ₹3.5L', user: 'Star Health' },
      { ts: '2026-04-08 10:00', event: 'Patient Discharged', user: 'Dr. Anand Krishnan' },
      { ts: '2026-04-09 14:00', event: 'Claim Submitted', user: 'Claims Team' },
      { ts: '2026-04-18 11:00', event: 'Query Raised — Missing Docs', user: 'Star Health TPA' },
      { ts: '2026-05-18 14:23', event: 'Under TPA Review', user: 'Star Health TPA' },
    ],
  },
  {
    id: 'CLM-2026-00821',
    patientName: 'Meena Nair',
    uhid: 'HC-004189',
    invoiceNo: 'INV-2026-01821',
    tpa: 'HDFC ERGO Health',
    claimType: 'CASHLESS',
    department: 'Orthopedics',
    doctor: 'Dr. Suresh Nair',
    branch: 'North Wing',
    claimAmount: 512000,
    approvedAmount: 512000,
    deniedAmount: 0,
    outstandingAmount: 512000,
    status: 'APPROVED',
    agingDays: 28,
    submissionDate: '2026-04-22',
    settlementStatus: 'PENDING',
    riskLevel: 'LOW',
    riskScore: 18,
    workflowStatus: 'Awaiting Settlement',
    lastUpdated: '2026-05-17 09:41',
    preAuthNo: 'PA-2026-03841',
    admissionDate: '2026-04-20',
    dischargeDate: '2026-04-25',
    age: 45, gender: 'Female',
    mobile: '9812345678',
    ward: 'Ortho Ward – Bed 12',
    diagnosis: 'Knee Replacement (Bilateral)',
    denialReasons: [],
    settlementHistory: [],
    arEntry: 'AR-2026-00398',
    glPosting: 'GL-2026-00821',
    leakage: false,
    leakageNote: null,
    aiDenialRisk: 12,
    aiRecoveryProb: 94,
    documents: ['Preauth Letter', 'Discharge Summary', 'OT Notes', 'Lab Reports', 'X-Rays'],
    missingDocs: [],
    timeline: [
      { ts: '2026-04-18 10:00', event: 'Preauth Submitted', user: 'TPA Desk' },
      { ts: '2026-04-19 16:30', event: 'Preauth Approved — ₹5.12L', user: 'HDFC ERGO' },
      { ts: '2026-04-20 08:00', event: 'Patient Admitted', user: 'Reception' },
      { ts: '2026-04-25 11:00', event: 'Patient Discharged', user: 'Dr. Suresh Nair' },
      { ts: '2026-04-26 14:00', event: 'Claim Submitted (Cashless)', user: 'Claims Team' },
      { ts: '2026-05-02 10:30', event: 'Claim Approved — ₹5.12L', user: 'HDFC ERGO' },
    ],
  },
  {
    id: 'CLM-2026-00784',
    patientName: 'Prakash Iyer',
    uhid: 'HC-003941',
    invoiceNo: 'INV-2026-01784',
    tpa: 'New India Assurance',
    claimType: 'REIMBURSEMENT',
    department: 'Neurology',
    doctor: 'Dr. Rajiv Menon',
    branch: 'East Block',
    claimAmount: 284000,
    approvedAmount: 0,
    deniedAmount: 284000,
    outstandingAmount: 284000,
    status: 'DENIED',
    agingDays: 78,
    submissionDate: '2026-03-02',
    settlementStatus: 'NOT_APPLICABLE',
    riskLevel: 'CRITICAL',
    riskScore: 92,
    workflowStatus: 'Appeal in Progress',
    lastUpdated: '2026-05-15 16:00',
    preAuthNo: null,
    admissionDate: '2026-02-28',
    dischargeDate: '2026-03-04',
    age: 62, gender: 'Male',
    mobile: '9845678901',
    ward: 'Neuro Ward – Bed 7',
    diagnosis: 'Ischemic Stroke',
    denialReasons: ['Pre-existing Condition', 'Missing Discharge Summary'],
    settlementHistory: [],
    arEntry: 'AR-2026-00312',
    glPosting: 'GL-2026-00784',
    leakage: true,
    leakageNote: 'Denial may be contestable — pre-existing clause review needed',
    aiDenialRisk: 92,
    aiRecoveryProb: 42,
    documents: ['Admission Summary', 'Lab Reports'],
    missingDocs: ['Discharge Summary', 'Previous Medical Records'],
    timeline: [
      { ts: '2026-02-28 08:30', event: 'Patient Admitted', user: 'Emergency' },
      { ts: '2026-03-04 12:00', event: 'Patient Discharged', user: 'Dr. Rajiv Menon' },
      { ts: '2026-03-08 14:00', event: 'Claim Submitted', user: 'Claims Team' },
      { ts: '2026-04-02 10:00', event: 'Claim Denied — Pre-existing', user: 'New India Assurance' },
      { ts: '2026-04-10 11:30', event: 'Appeal Filed', user: 'Claims Manager' },
      { ts: '2026-05-15 16:00', event: 'Appeal Under Review', user: 'New India Assurance' },
    ],
  },
  {
    id: 'CLM-2026-00762',
    patientName: 'Anitha Verma',
    uhid: 'HC-003824',
    invoiceNo: 'INV-2026-01762',
    tpa: 'CGHS',
    claimType: 'CGHS',
    department: 'Oncology',
    doctor: 'Dr. Kavita Iyer',
    branch: 'Specialty Center',
    claimAmount: 892000,
    approvedAmount: 756000,
    deniedAmount: 136000,
    outstandingAmount: 756000,
    status: 'PARTIAL_APPROVED',
    agingDays: 55,
    submissionDate: '2026-03-25',
    settlementStatus: 'PARTIAL',
    riskLevel: 'MEDIUM',
    riskScore: 52,
    workflowStatus: 'Partial Settlement Received',
    lastUpdated: '2026-05-14 11:20',
    preAuthNo: 'CGHS-2026-08412',
    admissionDate: '2026-03-18',
    dischargeDate: '2026-03-25',
    age: 51, gender: 'Female',
    mobile: '9867890123',
    ward: 'Oncology Ward – Bed 3',
    diagnosis: 'Breast Cancer — Chemotherapy Cycle 4',
    denialReasons: ['Exceeded Package Limit'],
    settlementHistory: [
      { date: '2026-05-10', amount: 420000, reference: 'CGHS/CHQ/4821', mode: 'Cheque' },
    ],
    arEntry: 'AR-2026-00284',
    glPosting: 'GL-2026-00762',
    leakage: true,
    leakageNote: '₹1.36L denied as excess over package — contestable',
    aiDenialRisk: 52,
    aiRecoveryProb: 64,
    documents: ['Preauth Letter', 'Discharge Summary', 'Chemo Sheets', 'Lab Reports'],
    missingDocs: ['Package Approval Extension Letter'],
    timeline: [
      { ts: '2026-03-15 09:00', event: 'CGHS Preauth Submitted', user: 'TPA Desk' },
      { ts: '2026-03-17 14:00', event: 'Preauth Approved — ₹7.56L', user: 'CGHS Office' },
      { ts: '2026-03-18 08:00', event: 'Patient Admitted', user: 'Oncology OPD' },
      { ts: '2026-03-25 12:00', event: 'Patient Discharged', user: 'Dr. Kavita Iyer' },
      { ts: '2026-03-28 10:00', event: 'Claim Submitted to CGHS', user: 'Claims Team' },
      { ts: '2026-05-05 11:00', event: 'Partial Approval — ₹7.56L (₹1.36L denied)', user: 'CGHS Office' },
      { ts: '2026-05-10 16:00', event: 'Partial Settlement ₹4.2L Received', user: 'Finance' },
    ],
  },
  {
    id: 'CLM-2026-00741',
    patientName: 'Sanjay Pillai',
    uhid: 'HC-003718',
    invoiceNo: 'INV-2026-01741',
    tpa: 'ICICI Lombard',
    claimType: 'TPA',
    department: 'ICU',
    doctor: 'Dr. Ashok Verma',
    branch: 'Main Campus',
    claimAmount: 621000,
    approvedAmount: 621000,
    deniedAmount: 0,
    outstandingAmount: 0,
    status: 'SETTLED',
    agingDays: 18,
    submissionDate: '2026-04-28',
    settlementStatus: 'SETTLED',
    riskLevel: 'LOW',
    riskScore: 8,
    workflowStatus: 'Closed',
    lastUpdated: '2026-05-16 10:00',
    preAuthNo: 'PA-2026-04218',
    admissionDate: '2026-04-22',
    dischargeDate: '2026-04-28',
    age: 67, gender: 'Male',
    mobile: '9812367890',
    ward: 'Medical ICU – Bed 2',
    diagnosis: 'Septic Shock',
    denialReasons: [],
    settlementHistory: [
      { date: '2026-05-16', amount: 621000, reference: 'ICICI/NEFT/2026/4218', mode: 'NEFT' },
    ],
    arEntry: 'AR-2026-00264',
    glPosting: 'GL-2026-00741',
    leakage: false,
    leakageNote: null,
    aiDenialRisk: 8,
    aiRecoveryProb: 98,
    documents: ['Preauth Letter', 'Discharge Summary', 'ICU Charts', 'Lab Reports', 'ECG Reports'],
    missingDocs: [],
    timeline: [
      { ts: '2026-04-22 02:30', event: 'Emergency Admission', user: 'Emergency' },
      { ts: '2026-04-23 10:00', event: 'Preauth Submitted (Emergency)', user: 'TPA Desk' },
      { ts: '2026-04-24 08:00', event: 'Preauth Approved — ₹6.21L', user: 'ICICI Lombard' },
      { ts: '2026-04-28 14:00', event: 'Patient Discharged', user: 'Dr. Ashok Verma' },
      { ts: '2026-04-29 11:00', event: 'Claim Submitted', user: 'Claims Team' },
      { ts: '2026-05-10 09:00', event: 'Claim Approved — ₹6.21L', user: 'ICICI Lombard' },
      { ts: '2026-05-16 10:00', event: 'Settlement Received — NEFT', user: 'Finance' },
      { ts: '2026-05-16 11:30', event: 'GL Posting & AR Closure', user: 'System' },
    ],
  },
  {
    id: 'CLM-2026-00719',
    patientName: 'Deepa Rao',
    uhid: 'HC-003612',
    invoiceNo: 'INV-2026-01719',
    tpa: 'Bajaj Allianz Health',
    claimType: 'CORPORATE',
    department: 'General Surgery',
    doctor: 'Dr. Meena Pillai',
    branch: 'South Clinic',
    claimAmount: 184000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 184000,
    status: 'SUBMITTED',
    agingDays: 14,
    submissionDate: '2026-05-06',
    settlementStatus: 'PENDING',
    riskLevel: 'LOW',
    riskScore: 22,
    workflowStatus: 'Awaiting TPA Review',
    lastUpdated: '2026-05-06 15:00',
    preAuthNo: 'PA-2026-04891',
    admissionDate: '2026-05-02',
    dischargeDate: '2026-05-05',
    age: 38, gender: 'Female',
    mobile: '9923456789',
    ward: 'Surgical Ward – Bed 8',
    diagnosis: 'Laparoscopic Cholecystectomy',
    denialReasons: [],
    settlementHistory: [],
    arEntry: 'AR-2026-00248',
    glPosting: 'GL-2026-00719',
    leakage: false,
    leakageNote: null,
    aiDenialRisk: 18,
    aiRecoveryProb: 91,
    documents: ['Preauth Letter', 'Discharge Summary', 'OT Notes', 'Anaesthesia Records'],
    missingDocs: [],
    timeline: [
      { ts: '2026-04-30 10:00', event: 'Preauth Submitted', user: 'TPA Desk' },
      { ts: '2026-05-01 14:00', event: 'Preauth Approved', user: 'Bajaj Allianz' },
      { ts: '2026-05-02 08:00', event: 'Patient Admitted', user: 'Admission' },
      { ts: '2026-05-05 15:00', event: 'Patient Discharged', user: 'Dr. Meena Pillai' },
      { ts: '2026-05-06 15:00', event: 'Claim Submitted', user: 'Claims Team' },
    ],
  },
  {
    id: 'CLM-2026-00698',
    patientName: 'Mohit Gupta',
    uhid: 'HC-003484',
    invoiceNo: 'INV-2026-01698',
    tpa: 'Medi Assist TPA',
    claimType: 'TPA',
    department: 'Nephrology',
    doctor: 'Dr. Sunitha Rao',
    branch: 'Main Campus',
    claimAmount: 430000,
    approvedAmount: 0,
    deniedAmount: 0,
    outstandingAmount: 430000,
    status: 'PENDING_DOCS',
    agingDays: 31,
    submissionDate: null,
    settlementStatus: 'NOT_APPLICABLE',
    riskLevel: 'HIGH',
    riskScore: 78,
    workflowStatus: 'Documents Pending',
    lastUpdated: '2026-05-13 09:00',
    preAuthNo: 'PA-2026-04012',
    admissionDate: '2026-04-18',
    dischargeDate: '2026-04-21',
    age: 54, gender: 'Male',
    mobile: '9834567890',
    ward: 'Nephrology – Bed 6',
    diagnosis: 'Acute Kidney Injury — Dialysis',
    denialReasons: [],
    settlementHistory: [],
    arEntry: 'AR-2026-00231',
    glPosting: null,
    leakage: true,
    leakageNote: 'Claim unsubmitted after 31 days — risk of late submission penalty',
    aiDenialRisk: 78,
    aiRecoveryProb: 52,
    documents: ['Preauth Letter', 'Admission Summary'],
    missingDocs: ['Discharge Summary', 'Dialysis Records', 'Lab Reports (Creatinine)', 'Nephrologist Certificate'],
    timeline: [
      { ts: '2026-04-17 14:00', event: 'Preauth Submitted', user: 'TPA Desk' },
      { ts: '2026-04-18 09:00', event: 'Preauth Approved', user: 'Medi Assist TPA' },
      { ts: '2026-04-18 10:00', event: 'Patient Admitted', user: 'Nephrology OPD' },
      { ts: '2026-04-21 13:00', event: 'Patient Discharged', user: 'Dr. Sunitha Rao' },
      { ts: '2026-05-01 10:00', event: 'Claim Preparation Started', user: 'Claims Team' },
      { ts: '2026-05-13 09:00', event: 'Documents Incomplete — Pending Upload', user: 'Claims Team' },
    ],
  },
  {
    id: 'CLM-2026-00672',
    patientName: 'Lakshmi Krishnan',
    uhid: 'HC-003298',
    invoiceNo: 'INV-2026-01672',
    tpa: 'ECHS Board',
    claimType: 'ECHS',
    department: 'Gynecology',
    doctor: 'Dr. Kavita Iyer',
    branch: 'Main Campus',
    claimAmount: 156000,
    approvedAmount: 156000,
    deniedAmount: 0,
    outstandingAmount: 0,
    status: 'RECONCILED',
    agingDays: 0,
    submissionDate: '2026-03-12',
    settlementStatus: 'SETTLED',
    riskLevel: 'LOW',
    riskScore: 4,
    workflowStatus: 'Closed & Reconciled',
    lastUpdated: '2026-05-02 10:30',
    preAuthNo: 'ECHS-2026-01248',
    admissionDate: '2026-03-08',
    dischargeDate: '2026-03-12',
    age: 34, gender: 'Female',
    mobile: '9856789012',
    ward: 'Gynae Ward – Bed 5',
    diagnosis: 'Normal Delivery',
    denialReasons: [],
    settlementHistory: [
      { date: '2026-04-28', amount: 156000, reference: 'ECHS/CHQ/2026/8412', mode: 'Cheque' },
    ],
    arEntry: 'AR-2026-00198',
    glPosting: 'GL-2026-00672',
    leakage: false,
    leakageNote: null,
    aiDenialRisk: 4,
    aiRecoveryProb: 100,
    documents: ['ECHS Auth Letter', 'Discharge Summary', 'Delivery Notes'],
    missingDocs: [],
    timeline: [
      { ts: '2026-03-08 06:00', event: 'Emergency Admission — Labour', user: 'Emergency' },
      { ts: '2026-03-12 08:00', event: 'Delivered & Discharged', user: 'Dr. Kavita Iyer' },
      { ts: '2026-03-14 10:00', event: 'ECHS Claim Submitted', user: 'Claims Team' },
      { ts: '2026-04-12 14:00', event: 'Claim Approved — ₹1.56L', user: 'ECHS Board' },
      { ts: '2026-04-28 16:00', event: 'Cheque Received — ₹1.56L', user: 'Finance' },
      { ts: '2026-05-02 10:30', event: 'AR Closure & GL Reconciled', user: 'System' },
    ],
  },
];

// ─── Workflow States for display ──────────────────────────────────────────────
export const WORKFLOW_STATES = [
  'Draft', 'Pending Documentation', 'Submitted', 'Under Review',
  'Approved', 'Partially Approved', 'Denied', 'Resubmitted',
  'Settled', 'Reconciled', 'Closed',
];

// ─── Grid Columns config ──────────────────────────────────────────────────────
export const GRID_COLUMNS = [
  { id: 'claimNo',     label: 'Claim No.',          width: 'w-36',  sticky: true  },
  { id: 'patient',     label: 'Patient',             width: 'w-44',  sticky: false },
  { id: 'uhid',        label: 'UHID',                width: 'w-28',  sticky: false },
  { id: 'invoice',     label: 'Invoice',             width: 'w-36',  sticky: false },
  { id: 'tpa',         label: 'Insurance / TPA',     width: 'w-44',  sticky: false },
  { id: 'type',        label: 'Type',                width: 'w-32',  sticky: false },
  { id: 'dept',        label: 'Department',          width: 'w-36',  sticky: false },
  { id: 'doctor',      label: 'Doctor',              width: 'w-40',  sticky: false },
  { id: 'claimAmt',    label: 'Claim Amt',           width: 'w-32',  sticky: false },
  { id: 'approvedAmt', label: 'Approved',            width: 'w-28',  sticky: false },
  { id: 'deniedAmt',   label: 'Denied',              width: 'w-28',  sticky: false },
  { id: 'outstanding', label: 'Outstanding',         width: 'w-28',  sticky: false },
  { id: 'status',      label: 'Claim Status',        width: 'w-36',  sticky: false },
  { id: 'aging',       label: 'Aging',               width: 'w-24',  sticky: false },
  { id: 'settlement',  label: 'Settlement',          width: 'w-32',  sticky: false },
  { id: 'risk',        label: 'Risk',                width: 'w-24',  sticky: false },
  { id: 'workflow',    label: 'Workflow',             width: 'w-44',  sticky: false },
  { id: 'updated',     label: 'Last Updated',        width: 'w-36',  sticky: false },
  { id: 'actions',     label: 'Actions',             width: 'w-20',  sticky: false },
];
