apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fact

resources:
  - ../../base

patches:
  - path: image-patch.yaml

configMapGenerator:
  - name: fact-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn
      - RATE_LIMIT_MAX=200
      - AUTH_RATE_LIMIT_MAX=20
