apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fact.fullname" . }}-uploads
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fact.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.uploads.accessMode }}
  {{- if .Values.uploads.storageClass }}
  storageClassName: {{ .Values.uploads.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.uploads.size }}
